<!DOCTYPE html>
<html lang="he" dir="rtl"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="ד״ר עדי שריד">
  <meta name="dcterms.date" content="2026-10-03">
  <title>ניתוח נתונים סטטיסטי – 3. רגרסיה לינארית מרובה</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-a7be01fb2db81efab316b33e5033add4.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- Slides use MathJax 2. Left alone it picks the STIX fonts installed on macOS,
       whose metrics misplace accents (the tilde in \tilde{\mu} drifts right).
       Force MathJax's own TeX web fonts so math looks the same on every machine. -->
  <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    "HTML-CSS": { availableFonts: [], preferredFont: null, webFont: "TeX" }
  });
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">3. רגרסיה לינארית מרובה</h1>
  <p class="subtitle">ניתוח נתונים סטטיסטי · הרצאה 3</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
ד״ר עדי שריד
</div>
</div>
</div>

  <p class="date">2026-10-03</p>
</section>
<section id="על-מה-נדבר-היום" class="slide level2">
<h2>על מה נדבר היום</h2>
<ul>
<li><strong>תזכורת:</strong> רגרסיה לינארית פשוטה, שיטת הריבועים הפחותים, ואיך קוראים את הפלט</li>
<li><strong>רגרסיה מרובה:</strong> כמה משתנים מסבירים, רישום מטריציוני, ופרשנות של “כל השאר קבוע”</li>
<li><strong>מבחני השערות:</strong> מבחן t לכל מקדם, מבחן F לכל המודל, ומבחן F חלקי</li>
<li><strong><span class="math inline">\(R^2\)</span> ו-<span class="math inline">\(R^2\)</span> מתוקן</strong></li>
<li><strong>משתנים קטגוריים ואינטראקציות</strong></li>
<li><strong>בדיקת ההנחות:</strong> שאריות ומולטיקולינאריות</li>
<li><strong>בחירת משתנים, רווחי סמך ורווחי חיזוי</strong></li>
</ul>
</section>
<section>
<section id="תזכורת-רגרסיה-לינארית-פשוטה-simple-linear-regression" class="title-slide slide level1 center">
<h1>תזכורת: רגרסיה לינארית פשוטה (<span class="en">Simple linear regression</span>)</h1>

</section>
<section id="השאלה-כמה-מעבד-צורכת-כל-אלף-בקשות" class="slide level2">
<h2>השאלה: כמה מעבד צורכת כל אלף בקשות?</h2>
<p>צוות התשתיות מתכנן קיבולת (<span class="en">capacity planning</span>) לשירות חדש. בעשרה חלונות זמן נמדדו העומס (אלפי בקשות בדקה) וניצולת המעבד (CPU, באחוזים).</p>
<p><strong>השאלות:</strong> בכמה עולה ניצולת המעבד עם כל אלף בקשות נוספות בדקה? והאם הקשר הזה “אמיתי”, או שהוא יכול להיות מקרי?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a>cpu <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">load =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="fl">11.5</span>, <span class="fl">14.5</span>, <span class="dv">12</span>, <span class="dv">15</span>, <span class="fl">16.6</span>, <span class="fl">12.5</span>, <span class="dv">13</span>, <span class="dv">14</span>, <span class="dv">17</span>),       <span class="co"># k requests / min</span></span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">util =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="fl">16.6</span>, <span class="fl">20.2</span>, <span class="fl">16.3</span>, <span class="fl">19.4</span>, <span class="fl">24.4</span>, <span class="dv">17</span>, <span class="fl">17.1</span>, <span class="fl">17.7</span>, <span class="fl">24.4</span>)  <span class="co"># CPU %</span></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="הנתונים" class="slide level2">
<h2>הנתונים</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cpu, <span class="fu">aes</span>(load, util)) <span class="sc">+</span></span>
<span id="cb2-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> nanas_pal[[<span class="st">"grey"</span>]], <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb2-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"ככל שהעומס עולה, המעבד עובד קשה יותר"</span>,</span>
<span id="cb2-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"עשרה חלונות זמן · הקו: קו הריבועים הפחותים"</span>,</span>
<span id="cb2-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Load (k requests / min)"</span>, <span class="at">y =</span> <span class="st">"CPU utilisation (%)"</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="03-multiple-regression_files/figure-html/cpu-plot-1.png" class="quarto-figure quarto-figure-center r-stretch" width="1200"></section>
<section id="המודל" class="slide level2 smaller">
<h2>המודל</h2>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i \qquad i = 1, \dots, n
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> הוא <strong>החותך</strong> (<span class="en">intercept</span>) ו-<span class="math inline">\(\beta_1\)</span> הוא <strong>השיפוע</strong> (<span class="en">slope</span>): בכמה משתנה התוחלת של <span class="math inline">\(Y\)</span> כש-<span class="math inline">\(x\)</span> עולה ביחידה אחת</li>
<li><span class="math inline">\(E(Y \mid x) = \beta_0 + \beta_1 x\)</span> ו-<span class="math inline">\(V(Y \mid x) = \sigma^2\)</span></li>
</ul>
<p><strong>ההנחות על השגיאות</strong> <span class="math inline">\(\varepsilon_i\)</span>:</p>
<ol type="1">
<li><strong>לינאריות:</strong> התוחלת של <span class="math inline">\(Y\)</span> היא פונקציה לינארית של <span class="math inline">\(x\)</span></li>
<li><strong>אי-תלות:</strong> השגיאות בלתי תלויות זו בזו</li>
<li><strong>שונות קבועה</strong> (<span class="en">homoscedasticity</span>): אותה <span class="math inline">\(\sigma^2\)</span> לכל ערך של <span class="math inline">\(x\)</span></li>
<li><strong>נורמליות:</strong> <span class="math inline">\(\varepsilon_i \sim N(0, \sigma^2)\)</span>. נדרשת למבחנים ולרווחי הסמך, לא לאמידה עצמה</li>
</ol>
</section>
<section id="שיטת-הריבועים-הפחותים-least-squares" class="slide level2 smaller">
<h2>שיטת הריבועים הפחותים (<span class="en">Least squares</span>)</h2>
<p>מחפשים את הקו שממזער את סכום ריבועי הסטיות האנכיות:</p>
<p><span class="math display">\[
L(\beta_0, \beta_1) = \sum_{i=1}^{n} \left(y_i - \beta_0 - \beta_1 x_i\right)^2
\]</span></p>
<p>גוזרים לפי <span class="math inline">\(\beta_0\)</span> ולפי <span class="math inline">\(\beta_1\)</span> ומשווים לאפס (<strong>משוואות נורמליות</strong>), ומקבלים:</p>
<p><span class="math display">\[
\hat\beta_1 = \frac{S_{xy}}{S_{xx}} \qquad \hat\beta_0 = \bar y - \hat\beta_1 \bar x
\]</span></p>
<p><span class="math display">\[
S_{xx} = \sum_{i=1}^{n} (x_i - \bar x)^2 = \sum x_i^2 - n\bar x^2 \qquad
S_{xy} = \sum_{i=1}^{n} (x_i - \bar x)(y_i - \bar y) = \sum x_i y_i - n \bar x \bar y
\]</span></p>
</section>
<section id="חישוב-ידני" class="slide level2 smaller">
<h2>חישוב ידני</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>cpu <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">x_bar =</span> <span class="fu">mean</span>(load), <span class="at">y_bar =</span> <span class="fu">mean</span>(util),</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>                 <span class="at">Sxx =</span> <span class="fu">sum</span>((load <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>                 <span class="at">Sxy =</span> <span class="fu">sum</span>((load <span class="sc">-</span> x_bar) <span class="sc">*</span> (util <span class="sc">-</span> y_bar)),</span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>                 <span class="at">Syy =</span> <span class="fu">sum</span>((util <span class="sc">-</span> y_bar)<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
      n x_bar y_bar   Sxx   Sxy   Syy
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    10  13.6  18.8  45.0  62.8  97.9</code></pre>
</div>
</div>
<p><span class="math display">\[
\hat\beta_1 = \frac{62.80}{44.99} = 1.396 \qquad
\hat\beta_0 = 18.81 - 1.396 \cdot 13.61 = -0.188
\]</span></p>
<p><span class="math display">\[
SS_R = \hat\beta_1 S_{xy} = 87.66 \qquad SS_E = S_{yy} - SS_R = 97.91 - 87.66 = 10.25 \qquad
\hat\sigma^2 = \frac{SS_E}{n-2} = 1.281
\]</span></p>
<p><span class="math display">\[
se(\hat\beta_1) = \sqrt{\frac{\hat\sigma^2}{S_{xx}}} = \sqrt{\frac{1.281}{44.99}} = 0.169 \qquad
t = \frac{1.396}{0.169} = 8.27 \qquad R^2 = \frac{SS_R}{S_{yy}} = 0.895
\]</span></p>
</section>
<section id="אותו-חישוב-ב-r" class="slide level2 smaller">
<h2>אותו חישוב ב-R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>fit_cpu <span class="ot">&lt;-</span> <span class="fu">lm</span>(util <span class="sc">~</span> load, <span class="at">data =</span> cpu)</span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_cpu)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = util ~ load, data = cpu)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6544 -0.7095 -0.0565  0.8273  1.4163 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.188      2.324   -0.08     0.94    
load           1.396      0.169    8.27  3.4e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.13 on 8 degrees of freedom
Multiple R-squared:  0.895, Adjusted R-squared:  0.882 
F-statistic: 68.4 on 1 and 8 DF,  p-value: 3.43e-05</code></pre>
</div>
</div>
</section>
<section id="איך-קוראים-את-הפלט" class="slide level2 smaller">
<h2>איך קוראים את הפלט</h2>
<ul>
<li><strong><code>Estimate</code></strong>: המקדמים. כל אלף בקשות נוספות בדקה מעלות את ניצולת המעבד ב-1.4 נקודות אחוז בממוצע</li>
<li><strong><code>Std. Error</code></strong>: שגיאת התקן של כל מקדם, <span class="math inline">\(se(\hat\beta_j)\)</span></li>
<li><strong><code>t value</code></strong> ו-<strong><code>Pr(&gt;|t|)</code></strong>: מבחן <span class="math inline">\(H_0: \beta_j = 0\)</span>, עם <span class="math inline">\(t = \hat\beta_j / se(\hat\beta_j)\)</span> ו-<span class="math inline">\(n - 2 = 8\)</span> דרגות חופש. לשיפוע <span class="math inline">\(p = 0.00003\)</span>, ולכן <strong>דוחים</strong>: הקשר לא מקרי</li>
<li><strong><code>Residual standard error</code></strong>: <span class="math inline">\(\hat\sigma = \sqrt{MS_E} = 1.13\)</span>. זו הסטייה הטיפוסית של תצפית מהקו, ביחידות של <span class="math inline">\(Y\)</span></li>
<li><strong><code>Multiple R-squared</code></strong>: 89.5% מהשונות בניצולת המעבד מוסברים על ידי העומס</li>
<li><strong><code>F-statistic</code></strong>: מבחן לכל המודל. ברגרסיה פשוטה <span class="math inline">\(F = t^2\)</span>: <span class="math inline">\(8.27^2 = 68.4\)</span></li>
</ul>
<aside class="notes">
<p>לשאול את הכיתה: למה החותך לא מובהק, ולמה שגיאת התקן שלו כל כך גדולה (2.3)? זה מוביל לשקף הבא.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="מה-עושים-עם-החותך-מירכוז-centering" class="slide level2 smaller">
<h2>מה עושים עם החותך? מירכוז (<span class="en">Centering</span>)</h2>
<p>החותך הוא הניצולת הצפויה כש-<span class="math inline">\(x = 0\)</span>, הרחק מטווח הנתונים (10 עד 17). לכן השונות שלו גדולה:</p>
<p><span class="math display">\[
V(\hat\beta_0) = \sigma^2 \left[\frac{1}{n} + \frac{\bar x^2}{S_{xx}}\right]
\]</span></p>
<p>אם מחסירים מ-<span class="math inline">\(x\)</span> את הממוצע שלו, <span class="math inline">\(\bar x = 0\)</span>, והחותך הופך ל-<span class="math inline">\(\bar y\)</span>: הניצולת הצפויה <strong>בעומס הממוצע</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(util <span class="sc">~</span> <span class="fu">I</span>(load <span class="sc">-</span> <span class="fu">mean</span>(load)), <span class="at">data =</span> cpu) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)            18.810     0.3579  52.551 1.906e-11
I(load - mean(load))    1.396     0.1688   8.272 3.431e-05</code></pre>
</div>
</div>
<ul>
<li>השיפוע לא השתנה, ושגיאת התקן של החותך ירדה מ-2.32 ל-<span class="math inline">\(\hat\sigma / \sqrt{n} = 1.132 / \sqrt{10} = 0.358\)</span></li>
<li>הקו הוא אותו קו. השתנתה רק השאלה שהחותך עונה עליה</li>
</ul>
</section>
<section id="פירוק-השונות-וטבלת-anova" class="slide level2 smaller">
<h2>פירוק השונות וטבלת ANOVA</h2>
<p><span class="math display">\[
\underbrace{\sum_{i}(y_i - \bar y)^2}_{SS_T} = \underbrace{\sum_{i}(\hat y_i - \bar y)^2}_{SS_R} + \underbrace{\sum_{i}(y_i - \hat y_i)^2}_{SS_E}
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>מקור</th>
<th>סכום ריבועים</th>
<th>דרגות חופש</th>
<th>ממוצע ריבועים</th>
<th><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>רגרסיה</td>
<td><span class="math inline">\(SS_R\)</span></td>
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(MS_R = SS_R / 1\)</span></td>
<td><span class="math inline">\(MS_R / MS_E\)</span></td>
</tr>
<tr class="even">
<td>שגיאה</td>
<td><span class="math inline">\(SS_E\)</span></td>
<td><span class="math inline">\(n - 2\)</span></td>
<td><span class="math inline">\(MS_E = SS_E / (n-2)\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>סך הכול</td>
<td><span class="math inline">\(SS_T\)</span></td>
<td><span class="math inline">\(n - 1\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_cpu)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: util
          Df Sum Sq Mean Sq F value  Pr(&gt;F)    
load       1   87.7    87.7    68.4 3.4e-05 ***
Residuals  8   10.2     1.3                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>מקדם המתאם המרובה:</strong> <span class="math inline">\(R^2 = SS_R / SS_T = 87.66 / 97.91 = 0.895\)</span></p>
<p>שני הרכיבים אי-שליליים, ולכן תמיד <span class="math inline">\(0 \le R^2 \le 1\)</span>.</p>
</section></section>
<section>
<section id="רגרסיה-לינארית-מרובה-multiple-linear-regression" class="title-slide slide level1 center">
<h1>רגרסיה לינארית מרובה (<span class="en">Multiple linear regression</span>)</h1>

</section>
<section id="השאלה-מה-קובע-את-זמן-התגובה-של-מודל-שפה" class="slide level2">
<h2>השאלה: מה קובע את זמן התגובה של מודל שפה?</h2>
<p>חברה משתמשת ב-API של מודל שפה, בשלושה גדלים: <code>small</code>, <code>medium</code> ו-<code>large</code>. המשתמשים מתלוננים על המתנה ארוכה.</p>
<p><strong>השאלות:</strong></p>
<ul>
<li>כמה זמן מוסיף כל טוקן (<span class="en">token</span>) בתשובה? וכל אלף טוקנים בקלט?</li>
<li>האם מודל השפה הגדול <strong>עצמו</strong> איטי יותר, או שהוא פשוט כותב תשובות ארוכות יותר?</li>
<li>כמה זמן תיקח קריאה עם 2,000 טוקנים בקלט ו-500 בפלט למודל השפה הגדול?</li>
</ul>
<p><strong>הנתונים:</strong> 250 קריאות מהלוגים (נתונים מדומים). לכל קריאה: גודל מודל השפה, מספר הטוקנים בקלט ובפלט, מספר המסמכים שצורפו לפרומפט (<span class="en">RAG</span>), השעה ביום, וזמן התגובה בשניות.</p>
</section>
<section id="הנתונים-1" class="slide level2">
<h2>הנתונים</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">303</span>)   <span class="co"># own seed, so edits elsewhere in the lecture don't change this example</span></span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a>n_calls <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb11-3"><a aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"small"</span>, <span class="st">"medium"</span>, <span class="st">"large"</span>)</span>
<span id="cb11-4"><a aria-hidden="true" tabindex="-1"></a>median_output <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">small =</span> <span class="dv">250</span>,   <span class="at">medium =</span> <span class="dv">350</span>,   <span class="at">large =</span> <span class="dv">500</span>)    <span class="co"># tokens</span></span>
<span id="cb11-5"><a aria-hidden="true" tabindex="-1"></a>sec_per_token <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">small =</span> <span class="fl">0.010</span>, <span class="at">medium =</span> <span class="fl">0.018</span>, <span class="at">large =</span> <span class="fl">0.030</span>)</span>
<span id="cb11-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a aria-hidden="true" tabindex="-1"></a>llm <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">model    =</span> <span class="fu">factor</span>(<span class="fu">sample</span>(sizes, n_calls, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>)), sizes),</span>
<span id="cb11-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">rag_docs =</span> <span class="fu">rpois</span>(n_calls, <span class="dv">3</span>),                         <span class="co"># documents added to the prompt</span></span>
<span id="cb11-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">input_tokens  =</span> <span class="fu">round</span>(<span class="dv">300</span> <span class="sc">+</span> <span class="dv">550</span> <span class="sc">*</span> rag_docs <span class="sc">+</span> <span class="fu">rlnorm</span>(n_calls, <span class="fu">log</span>(<span class="dv">400</span>), <span class="fl">0.6</span>)),</span>
<span id="cb11-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">output_tokens =</span> <span class="fu">round</span>(<span class="fu">rlnorm</span>(n_calls, <span class="fu">log</span>(median_output[<span class="fu">as.character</span>(model)]), <span class="fl">0.5</span>)),</span>
<span id="cb11-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">hour     =</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">23</span>, n_calls, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-13"><a aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb11-14"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">latency =</span> <span class="fl">0.8</span> <span class="sc">+</span> <span class="fl">0.25</span> <span class="sc">*</span> input_tokens <span class="sc">/</span> <span class="dv">1000</span> <span class="sc">+</span></span>
<span id="cb11-15"><a aria-hidden="true" tabindex="-1"></a>           sec_per_token[<span class="fu">as.character</span>(model)] <span class="sc">*</span> output_tokens <span class="sc">+</span> <span class="fu">rnorm</span>(n_calls, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb11-16"><a aria-hidden="true" tabindex="-1"></a>         <span class="at">latency =</span> <span class="fu">round</span>(latency, <span class="dv">2</span>),</span>
<span id="cb11-17"><a aria-hidden="true" tabindex="-1"></a>         <span class="at">input_k =</span> input_tokens <span class="sc">/</span> <span class="dv">1000</span>)</span>
<span id="cb11-18"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a aria-hidden="true" tabindex="-1"></a>llm <span class="sc">|&gt;</span> <span class="fu">select</span>(model, input_tokens, output_tokens, rag_docs, hour, latency) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">4</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  model  input_tokens output_tokens rag_docs  hour latency
  &lt;fct&gt;         &lt;dbl&gt;         &lt;dbl&gt;    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
1 small          3585           155        5    21    1.71
2 large          1851           478        0     1   15.7 
3 medium         3140           161        5    16    3.89
4 medium         2382           200        3     6    4.83</code></pre>
</div>
</div>
</section>
<section id="זמן-התגובה-מול-אורך-התשובה" class="slide level2">
<h2>זמן התגובה מול אורך התשובה</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(llm, <span class="fu">aes</span>(output_tokens, latency, <span class="at">colour =</span> model)) <span class="sc">+</span></span>
<span id="cb13-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> model_cols) <span class="sc">+</span></span>
<span id="cb13-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"תשובה ארוכה יותר, המתנה ארוכה יותר"</span>,</span>
<span id="cb13-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"וכל מודל שפה עם שיפוע משלו"</span>,</span>
<span id="cb13-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Output tokens"</span>, <span class="at">y =</span> <span class="st">"Latency (s)"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="זמן-התגובה-מול-אורך-התשובה-output" class="slide level2 output-location-slide"><h2>זמן התגובה מול אורך התשובה</h2><div class="cell output-location-slide" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="03-multiple-regression_files/figure-html/llm-plot-1.png" class="quarto-figure quarto-figure-center" width="1200"></p>
</figure>
</div>
</div>
</div></section><section id="המודל-1" class="slide level2 smaller">
<h2>המודל</h2>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_k x_{ik} + \varepsilon_i \qquad \varepsilon_i \sim N(0, \sigma^2)
\]</span></p>
<ul>
<li>אותן הנחות כמו ברגרסיה פשוטה, עם <span class="math inline">\(k\)</span> משתנים מסבירים (<span class="en">predictors</span>)</li>
<li><strong>הפרשנות של <span class="math inline">\(\beta_j\)</span>:</strong> השינוי בתוחלת של <span class="math inline">\(Y\)</span> כש-<span class="math inline">\(x_j\)</span> עולה ביחידה אחת, <strong>וכל שאר המשתנים במודל נשארים קבועים</strong></li>
<li>“לינארי” פירושו לינארי <strong>בפרמטרים</strong> <span class="math inline">\(\beta\)</span>. אפשר להכניס <span class="math inline">\(x^2\)</span>, <span class="math inline">\(\log x\)</span> או מכפלה <span class="math inline">\(x_1 x_2\)</span>, והמודל עדיין לינארי</li>
</ul>
<p>נתחיל משני משתנים מסבירים: הטוקנים בקלט (באלפים) והטוקנים בפלט.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> output_tokens, <span class="at">data =</span> llm)</span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit2)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       input_k output_tokens 
     -1.75379       0.07958       0.02634 </code></pre>
</div>
</div>
</section>
<section id="רישום-מטריציוני-matrix-form" class="slide level2 smaller">
<h2>רישום מטריציוני (<span class="en">Matrix form</span>)</h2>
<p><span class="math display">\[
\mathbf{y} = X\boldsymbol\beta + \boldsymbol\varepsilon \qquad
X = \begin{pmatrix} 1 &amp; x_{11} &amp; \cdots &amp; x_{1k} \\ \vdots &amp; \vdots &amp; &amp; \vdots \\ 1 &amp; x_{n1} &amp; \cdots &amp; x_{nk} \end{pmatrix}_{n \times (k+1)}
\]</span></p>
<p>ממזערים את <span class="math inline">\(L(\boldsymbol\beta) = (\mathbf{y} - X\boldsymbol\beta)'(\mathbf{y} - X\boldsymbol\beta)\)</span>. הנגזרת היא <span class="math inline">\(-2X'\mathbf{y} + 2X'X\boldsymbol\beta\)</span>, ומשווים אותה לאפס:</p>
<p><span class="math display">\[
X'X\hat{\boldsymbol\beta} = X'\mathbf{y} \quad\Longrightarrow\quad \hat{\boldsymbol\beta} = (X'X)^{-1}X'\mathbf{y}
\]</span></p>
<ul>
<li>העמודה של אחדות ב-<span class="math inline">\(X\)</span> היא החותך</li>
<li>צריך ש-<span class="math inline">\(X'X\)</span> תהיה הפיכה: אף משתנה לא יכול להיות צירוף לינארי מדויק של האחרים</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> input_k <span class="sc">+</span> output_tokens, <span class="at">data =</span> llm)   <span class="co"># adds the column of ones</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> llm<span class="sc">$</span>latency</span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y                            <span class="co"># same as coef(fit2)</span></span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  [,1]
(Intercept)   -1.75379
input_k        0.07958
output_tokens  0.02634</code></pre>
</div>
</div>
</section>
<section id="תכונות-האומדים" class="slide level2 smaller">
<h2>תכונות האומדים</h2>
<ul>
<li><strong>חסרי הטיה:</strong> <span class="math inline">\(E(\hat{\boldsymbol\beta}) = \boldsymbol\beta\)</span></li>
<li><strong>מטריצת השונויות:</strong> <span class="math inline">\(V(\hat{\boldsymbol\beta}) = \sigma^2 (X'X)^{-1}\)</span>. נסמן <span class="math inline">\(C = (X'X)^{-1}\)</span></li>
<li><strong>אומד ל-<span class="math inline">\(\sigma^2\)</span>:</strong> <span class="math inline">\(\hat\sigma^2 = MS_E = \dfrac{SS_E}{n - k - 1}\)</span>. מאבדים דרגת חופש על כל מקדם, כולל החותך</li>
</ul>
<p><span class="math display">\[
se(\hat\beta_j) = \sqrt{\hat\sigma^2 C_{jj}} \qquad
t = \frac{\hat\beta_j}{se(\hat\beta_j)} \sim t_{n-k-1} \qquad
\hat\beta_j \pm t_{1-\alpha/2,\, n-k-1} \cdot se(\hat\beta_j)
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a>sigma2_hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(fit2)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (<span class="fu">nrow</span>(X) <span class="sc">-</span> <span class="fu">ncol</span>(X))     <span class="co"># SSE / (n - k - 1)</span></span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(sigma2_hat <span class="sc">*</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)))                  <span class="co"># = "Std. Error" in summary()</span></span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       input_k output_tokens 
    0.7254406     0.2442116     0.0009362 </code></pre>
</div>
</div>
</section>
<section id="הפלט-המלא" class="slide level2 smaller">
<h2>הפלט המלא</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = latency ~ input_k + output_tokens, data = llm)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.084  -1.880  -0.418   1.786   9.959 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -1.753788   0.725441   -2.42    0.016 *  
input_k        0.079583   0.244212    0.33    0.745    
output_tokens  0.026340   0.000936   28.13   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.56 on 247 degrees of freedom
Multiple R-squared:  0.762, Adjusted R-squared:  0.76 
F-statistic:  396 on 2 and 247 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="איך-קוראים-את-הפלט-1" class="slide level2 smaller">
<h2>איך קוראים את הפלט</h2>
<ul>
<li><strong><code>output_tokens = 0.0263</code></strong>: כל טוקן נוסף בתשובה מוסיף כ-26 מילישניות, <strong>כשמספר הטוקנים בקלט קבוע</strong>. <span class="math inline">\(t = 28\)</span>, מובהק מאוד</li>
<li><strong><code>input_k</code></strong>: לא מובהק (<span class="math inline">\(p = 0.75\)</span>). האם הקלט באמת לא משפיע? נחזור לזה</li>
<li><strong><code>F-statistic: 396 on 2 and 247 DF</code></strong>: מבחן לכל המודל. <span class="math inline">\(k = 2\)</span> ו-<span class="math inline">\(n - k - 1 = 247\)</span></li>
<li><strong><code>R-squared = 0.762</code></strong>: שני המשתנים יחד מסבירים 76% מהשונות בזמן התגובה</li>
<li><strong><code>Residual standard error = 3.56</code></strong>: קריאה טיפוסית רחוקה 3.6 שניות מהחיזוי. זה הרבה, כשהחציון הוא 6 שניות</li>
</ul>
<aside class="notes">
<p>input_k יוצא לא מובהק כי המודל עדיין שגוי: הוא מתעלם מגודל מודל השפה, וכל הרעש הזה נכנס לשגיאה ומסתיר את האפקט. אל תגלו להם עדיין, זה יתגלה בהמשך.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="מבחני-השערות-במודל-המרובה" class="title-slide slide level1 center">
<h1>מבחני השערות במודל המרובה</h1>

</section>
<section id="מבחן-f-לכל-המודל" class="slide level2 smaller">
<h2>מבחן F לכל המודל</h2>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \dots = \beta_k = 0 \qquad H_1: \text{לפחות מקדם אחד שונה מאפס}
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>מקור</th>
<th>סכום ריבועים</th>
<th>דרגות חופש</th>
<th>ממוצע ריבועים</th>
<th><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>רגרסיה</td>
<td><span class="math inline">\(SS_R\)</span></td>
<td><span class="math inline">\(k\)</span></td>
<td><span class="math inline">\(MS_R = SS_R / k\)</span></td>
<td><span class="math inline">\(MS_R / MS_E\)</span></td>
</tr>
<tr class="even">
<td>שגיאה</td>
<td><span class="math inline">\(SS_E\)</span></td>
<td><span class="math inline">\(n - k - 1\)</span></td>
<td><span class="math inline">\(MS_E = SS_E / (n-k-1)\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>סך הכול</td>
<td><span class="math inline">\(SS_T\)</span></td>
<td><span class="math inline">\(n - 1\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>דוחים את <span class="math inline">\(H_0\)</span> אם <span class="math inline">\(F &gt; F_{1-\alpha;\, k,\, n-k-1}\)</span>.</p>
<ul>
<li>דחייה אומרת רק שלפחות משתנה <strong>אחד</strong> עוזר. היא לא אומרת איזה</li>
<li>מבחני ה-t בודקים כל מקדם <strong>בנוכחות כל השאר</strong>. משתנה יכול להיות לא מובהק לבד, ובכל זאת חשוב</li>
</ul>
</section>
<section id="r2-ו-r2-מתוקן-adjusted-r²" class="slide level2 smaller">
<h2><span class="math inline">\(R^2\)</span> ו-<span class="math inline">\(R^2\)</span> מתוקן (<span class="en">Adjusted R²</span>)</h2>
<p><span class="math display">\[
R^2 = \frac{SS_R}{SS_T} = 1 - \frac{SS_E}{SS_T} \qquad
R^2_{adj} = 1 - \frac{SS_E / (n - k - 1)}{SS_T / (n - 1)} = 1 - (1 - R^2)\frac{n - 1}{n - k - 1}
\]</span></p>
<ul>
<li><strong>הבעיה של <span class="math inline">\(R^2\)</span>:</strong> הוא <strong>אף פעם לא יורד</strong> כשמוסיפים משתנה, גם אם המשתנה הוא רעש טהור</li>
<li><strong><span class="math inline">\(R^2\)</span> המתוקן</strong> “מעניש” על כל משתנה נוסף. הוא עולה רק אם המשתנה מקטין את <span class="math inline">\(MS_E\)</span>. למקסם אותו זה כמו למזער את <span class="math inline">\(MS_E\)</span></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8</span>)</span>
<span id="cb22-2"><a aria-hidden="true" tabindex="-1"></a>llm_noise <span class="ot">&lt;-</span> llm <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">noise1 =</span> <span class="fu">rnorm</span>(<span class="fu">n</span>()), <span class="at">noise2 =</span> <span class="fu">rnorm</span>(<span class="fu">n</span>()), <span class="at">noise3 =</span> <span class="fu">rnorm</span>(<span class="fu">n</span>()))</span>
<span id="cb22-3"><a aria-hidden="true" tabindex="-1"></a>fit_noise <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> output_tokens <span class="sc">+</span> noise1 <span class="sc">+</span> noise2 <span class="sc">+</span> noise3, <span class="at">data =</span> llm_noise)</span>
<span id="cb22-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">fit2      =</span> <span class="fu">c</span>(<span class="at">R2 =</span> <span class="fu">summary</span>(fit2)<span class="sc">$</span>r.squared,      <span class="at">adj =</span> <span class="fu">summary</span>(fit2)<span class="sc">$</span>adj.r.squared),</span>
<span id="cb22-5"><a aria-hidden="true" tabindex="-1"></a>      <span class="at">fit_noise =</span> <span class="fu">c</span>(<span class="at">R2 =</span> <span class="fu">summary</span>(fit_noise)<span class="sc">$</span>r.squared, <span class="at">adj =</span> <span class="fu">summary</span>(fit_noise)<span class="sc">$</span>adj.r.squared))</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              R2    adj
fit2      0.7622 0.7603
fit_noise 0.7628 0.7580</code></pre>
</div>
</div>
</section>
<section id="תרגיל-השלימו-את-הפלט" class="slide level2 smaller">
<h2>תרגיל: השלימו את הפלט</h2>
<p>פלט של רגרסיה עם <span class="math inline">\(n = 30\)</span> תצפיות ו-<span class="math inline">\(k = 3\)</span> משתנים מסבירים. חלק מהערכים נמחקו:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>מקור</th>
<th>סכום ריבועים</th>
<th>דרגות חופש</th>
<th>ממוצע ריבועים</th>
<th><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>רגרסיה</td>
<td>600</td>
<td>(א)</td>
<td>(ב)</td>
<td>(ג)</td>
</tr>
<tr class="even">
<td>שגיאה</td>
<td>(ד)</td>
<td>(ה)</td>
<td>(ו)</td>
<td></td>
</tr>
<tr class="odd">
<td>סך הכול</td>
<td>860</td>
<td>29</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>השלימו את הטבלה, וחשבו את <span class="math inline">\(R^2\)</span>, את <span class="math inline">\(R^2_{adj}\)</span> ואת <span class="math inline">\(\hat\sigma\)</span>. האם המודל מובהק ב-<span class="math inline">\(\alpha = 0.05\)</span>? (<span class="math inline">\(F_{0.95;\,3,\,26} = 2.98\)</span>)</p>
</section></section>
<section>
<section id="משתנים-קטגוריים-categorical-variables" class="title-slide slide level1 center">
<h1>משתנים קטגוריים (<span class="en">Categorical variables</span>)</h1>

</section>
<section id="משתני-דמה-dummy-variables" class="slide level2 smaller">
<h2>משתני דמה (<span class="en">Dummy variables</span>)</h2>
<p>למשתנה קטגורי עם <span class="math inline">\(m\)</span> רמות מוסיפים <span class="math inline">\(m - 1\)</span> <strong>משתני דמה</strong> (אינדיקטורים). רמה אחת היא <strong>רמת הבסיס</strong> (<span class="en">reference level</span>), ולה אין משתנה משלה.</p>
<p><span class="math display">\[
D_{medium} = \begin{cases} 1 &amp; \text{medium} \\ 0 &amp; \text{אחרת} \end{cases} \qquad
D_{large} = \begin{cases} 1 &amp; \text{large} \\ 0 &amp; \text{אחרת} \end{cases}
\]</span></p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_{input} + \beta_2 x_{output} + \beta_3 D_{medium} + \beta_4 D_{large} + \varepsilon
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_4\)</span>: בכמה קריאה למודל השפה הגדול איטית יותר מקריאה למודל השפה הקטן, <strong>באותו מספר טוקנים</strong></li>
<li>למה לא <span class="math inline">\(m\)</span> משתנים? כי אז <span class="math inline">\(D_{small} + D_{medium} + D_{large} = 1\)</span>, בדיוק כמו עמודת החותך, ו-<span class="math inline">\(X'X\)</span> לא הפיכה</li>
<li>R יוצר את משתני הדמה בעצמו מכל <code>factor</code>. רמת הבסיס היא הרמה הראשונה (<code>levels</code>)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(<span class="sc">~</span> model, <span class="at">data =</span> llm) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">3</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) modelmedium modellarge
1           1           0          0
2           1           0          1
3           1           1          0</code></pre>
</div>
</div>
</section>
<section id="האם-מודל-השפה-הגדול-איטי-יותר" class="slide level2 smaller">
<h2>האם מודל השפה הגדול איטי יותר?</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a>fit_raw <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> model, <span class="at">data =</span> llm)                            <span class="co"># model only</span></span>
<span id="cb26-2"><a aria-hidden="true" tabindex="-1"></a>fit3    <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> output_tokens <span class="sc">+</span> model, <span class="at">data =</span> llm)  <span class="co"># same length of answer</span></span>
<span id="cb26-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">raw =</span> <span class="fu">coef</span>(fit_raw)[<span class="fu">c</span>(<span class="st">"modelmedium"</span>, <span class="st">"modellarge"</span>)],</span>
<span id="cb26-4"><a aria-hidden="true" tabindex="-1"></a>      <span class="at">adjusted =</span> <span class="fu">coef</span>(fit3)[<span class="fu">c</span>(<span class="st">"modelmedium"</span>, <span class="st">"modellarge"</span>)])</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         modelmedium modellarge
raw            4.930     15.182
adjusted       2.047      9.018</code></pre>
</div>
</div>
<ul>
<li><strong>בלי לשלוט באורך התשובה:</strong> קריאה למודל השפה הגדול איטית ב-15.2 שניות מקריאה למודל השפה הקטן</li>
<li><strong>באותו מספר טוקנים:</strong> הפער יורד ל-9 שניות</li>
<li>חלק מהפער נובע מכך שמודל השפה הגדול כותב תשובות ארוכות יותר. זה <strong>משתנה מערבב</strong> (<span class="en">confounder</span>)</li>
<li>“שליטה” במשתנה (<span class="en">controlling for</span>) פירושה להשוות קריאות עם אותו ערך שלו</li>
</ul>
</section>
<section id="מבחן-f-חלקי-partial-f-test" class="slide level2 smaller">
<h2>מבחן F חלקי (<span class="en">Partial F test</span>)</h2>
<p><strong>השאלה:</strong> האם גודל מודל השפה משפיע בכלל? זו השערה על <strong>שני</strong> מקדמים יחד, <span class="math inline">\(H_0: \beta_3 = \beta_4 = 0\)</span>. אי אפשר לענות עליה עם שני מבחני t נפרדים.</p>
<p>משווים בין <strong>המודל המלא</strong> (<span class="en">full</span>) לבין <strong>המודל המצומצם</strong> (<span class="en">reduced</span>), שבו <span class="math inline">\(H_0\)</span> נכונה:</p>
<p><span class="math display">\[
F = \frac{(SS_E^{R} - SS_E^{F}) / q}{SS_E^{F} / (n - k - 1)} \sim F_{q,\; n-k-1}
\]</span></p>
<p><span class="math inline">\(q\)</span> הוא מספר המקדמים שנבדקים, ו-<span class="math inline">\(k\)</span> הוא מספר המשתנים במודל <strong>המלא</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit2, fit3)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: latency ~ input_k + output_tokens
Model 2: latency ~ input_k + output_tokens + model
  Res.Df  RSS Df Sum of Sq   F Pr(&gt;F)    
1    247 3125                            
2    245  911  2      2213 297 &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="איך-קוראים-את-הפלט-2" class="slide level2">
<h2>איך קוראים את הפלט</h2>
<ul>
<li><strong><code>RSS</code></strong>: סכום ריבועי השגיאות (<span class="math inline">\(SS_E\)</span>) של כל מודל. משתני הדמה הורידו אותו מ-3125 ל-911</li>
<li><strong><code>Df = 2</code></strong>: הוספנו <span class="math inline">\(q = 2\)</span> מקדמים</li>
<li><strong>בחישוב ידני</strong> (דוחים את <span class="math inline">\(H_0\)</span>: גודל מודל השפה משפיע):</li>
</ul>
<p><span class="math display">\[
F = \frac{(3125 - 911) / 2}{911 / 245} = 297
\]</span></p>
<ul>
<li>כש-<span class="math inline">\(q = 1\)</span>, מבחן F החלקי שקול למבחן t של אותו מקדם: <span class="math inline">\(F = t^2\)</span></li>
<li>מבחן F לכל המודל הוא מקרה פרטי: המודל המצומצם הוא מודל עם חותך בלבד</li>
</ul>
</section></section>
<section>
<section id="אינטראקציות-interactions" class="title-slide slide level1 center">
<h1>אינטראקציות (<span class="en">Interactions</span>)</h1>

</section>
<section id="האם-הקווים-מקבילים" class="slide level2">
<h2>האם הקווים מקבילים?</h2>
<p>ברגרסיה <code>fit3</code> לכל מודל שפה יש חותך משלו, אבל <strong>אותו שיפוע</strong>: אותו זמן לכל טוקן בתשובה. זה סביר?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">augment</span>(fit3), <span class="fu">aes</span>(output_tokens, <span class="at">colour =</span> model)) <span class="sc">+</span></span>
<span id="cb30-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> latency), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> model_cols) <span class="sc">+</span></span>
<span id="cb30-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"קווים מקבילים לא מתאימים לנתונים"</span>,</span>
<span id="cb30-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"הקווים: החיזוי של רגרסיה בלי אינטראקציה (בממוצע הקלט)"</span>,</span>
<span id="cb30-7"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Output tokens"</span>, <span class="at">y =</span> <span class="st">"Latency (s)"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="האם-הקווים-מקבילים-output" class="slide level2 output-location-slide"><h2>האם הקווים מקבילים?</h2><div class="cell output-location-slide" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="03-multiple-regression_files/figure-html/parallel-lines-1.png" class="quarto-figure quarto-figure-center" width="1200"></p>
</figure>
</div>
</div>
</div></section><section id="מודל-עם-אינטראקציה" class="slide level2 smaller">
<h2>מודל עם אינטראקציה</h2>
<p><strong>אינטראקציה</strong> פירושה שההשפעה של משתנה אחד תלויה בערך של משתנה אחר. כאן: הזמן לכל טוקן תלוי בגודל מודל השפה.</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_{in} + \beta_2 x_{out} + \beta_3 D_{med} + \beta_4 D_{lrg} + \beta_5\, x_{out} D_{med} + \beta_6\, x_{out} D_{lrg} + \varepsilon
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>מודל שפה</th>
<th>השיפוע של <span class="math inline">\(x_{out}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>small</td>
<td><span class="math inline">\(\beta_2\)</span></td>
</tr>
<tr class="even">
<td>medium</td>
<td><span class="math inline">\(\beta_2 + \beta_5\)</span></td>
</tr>
<tr class="odd">
<td>large</td>
<td><span class="math inline">\(\beta_2 + \beta_6\)</span></td>
</tr>
</tbody>
</table>
<p>ב-R, <code>output_tokens * model</code> הוא קיצור של <code>output_tokens + model + output_tokens:model</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> output_tokens <span class="sc">*</span> model, <span class="at">data =</span> llm)</span>
<span id="cb31-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit4)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="מודל-עם-אינטראקציה-output" class="slide level2 smaller output-location-slide"><h2>מודל עם אינטראקציה</h2><div class="cell output-location-slide" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = latency ~ input_k + output_tokens * model, data = llm)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3999 -0.7069  0.0906  0.6431  2.3889 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                0.917850   0.224929    4.08  6.1e-05 ***
input_k                    0.220542   0.064231    3.43   0.0007 ***
output_tokens              0.009887   0.000532   18.57  &lt; 2e-16 ***
modelmedium               -0.075828   0.278457   -0.27   0.7856    
modellarge                -0.613472   0.384691   -1.59   0.1121    
output_tokens:modelmedium  0.008135   0.000690   11.80  &lt; 2e-16 ***
output_tokens:modellarge   0.021030   0.000749   28.09  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.931 on 243 degrees of freedom
Multiple R-squared:  0.984, Adjusted R-squared:  0.984 
F-statistic: 2.49e+03 on 6 and 243 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div></section><section id="איך-קוראים-את-הפלט-3" class="slide level2 smaller">
<h2>איך קוראים את הפלט</h2>
<ul>
<li><strong>זמן לכל טוקן בתשובה:</strong> 9.9 מילישניות במודל השפה הקטן, 18 בבינוני ו-30.9 בגדול (האמת בסימולציה: 10, 18 ו-30)</li>
<li><strong><code>input_k</code></strong> מובהק עכשיו: 0.22 שניות לכל אלף טוקנים בקלט. במודלים הקודמים הוא “הוסתר” בגלל שגיאה גדולה (<span class="math inline">\(\hat\sigma = 3.6\)</span>). עכשיו <span class="math inline">\(\hat\sigma = 0.93\)</span></li>
<li><strong><code>modelmedium</code>, <code>modellarge</code></strong> לא מובהקים, אבל <strong>לא מוחקים אותם</strong>. כשיש אינטראקציה, הם ההפרש בין מודלי השפה כשאורך התשובה <strong>אפס</strong>, ולא “ההשפעה של גודל מודל השפה”</li>
<li><strong>כלל ההיררכיה:</strong> אם אינטראקציה נמצאת במודל, משאירים בו גם את המשתנים שמרכיבים אותה</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit3, fit4)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: latency ~ input_k + output_tokens + model
Model 2: latency ~ input_k + output_tokens * model
  Res.Df RSS Df Sum of Sq   F Pr(&gt;F)    
1    245 911                            
2    243 211  2       701 404 &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section></section>
<section>
<section id="בדיקת-ההנחות-diagnostics" class="title-slide slide level1 center">
<h1>בדיקת ההנחות (<span class="en">Diagnostics</span>)</h1>

</section>
<section id="שאריות-מול-ערכים-חזויים" class="slide level2">
<h2>שאריות מול ערכים חזויים</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="st">`</span><span class="at">בלי אינטראקציה (fit3)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">augment</span>(fit3),</span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>          <span class="st">`</span><span class="at">עם אינטראקציה (fit4)</span><span class="st">`</span>  <span class="ot">=</span> <span class="fu">augment</span>(fit4), <span class="at">.id =</span> <span class="st">"fit"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(.fitted, .resid, <span class="at">colour =</span> model)) <span class="sc">+</span></span>
<span id="cb35-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> nanas_pal[[<span class="st">"grey"</span>]]) <span class="sc">+</span></span>
<span id="cb35-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> fit, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> model_cols) <span class="sc">+</span></span>
<span id="cb35-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"השאריות חושפות את מה שהרגרסיה פספסה"</span>,</span>
<span id="cb35-9"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"משמאל: דפוס ברור לפי גודל מודל השפה · מימין: ענן אקראי סביב אפס"</span>,</span>
<span id="cb35-10"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fitted value (s)"</span>, <span class="at">y =</span> <span class="st">"Residual (s)"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="שאריות-מול-ערכים-חזויים-output" class="slide level2 output-location-slide"><h2>שאריות מול ערכים חזויים</h2><div class="cell output-location-slide" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="03-multiple-regression_files/figure-html/resid-plot-1.png" class="quarto-figure quarto-figure-center" width="1200"></p>
</figure>
</div>
</div>
</div></section><section id="מה-מחפשים-בגרף-השאריות" class="slide level2 smaller">
<h2>מה מחפשים בגרף השאריות</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>מה רואים</th>
<th>מה זה אומר</th>
<th>מה עושים</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ענן אקראי סביב אפס</td>
<td>ההנחות סבירות</td>
<td></td>
</tr>
<tr class="even">
<td>עקומה (קשת)</td>
<td>הקשר לא לינארי</td>
<td>מוסיפים <span class="math inline">\(x^2\)</span>, טרנספורמציה ל-<span class="math inline">\(x\)</span></td>
</tr>
<tr class="odd">
<td>משפך: הפיזור גדל עם <span class="math inline">\(\hat y\)</span></td>
<td>השונות לא קבועה</td>
<td>טרנספורמציה ל-<span class="math inline">\(Y\)</span> (למשל <span class="math inline">\(\log Y\)</span>)</td>
</tr>
<tr class="even">
<td>קבוצות עם דפוסים שונים</td>
<td>חסר משתנה או אינטראקציה</td>
<td>מוסיפים אותם למודל</td>
</tr>
<tr class="odd">
<td>נקודה בודדת רחוקה</td>
<td>ערך חריג</td>
<td>בודקים אותו. לא מוחקים אוטומטית</td>
</tr>
</tbody>
</table>
<p><strong>ועוד שתי בדיקות:</strong></p>
<ul>
<li><strong>נורמליות:</strong> גרף <span class="en">Q-Q</span> של השאריות (<code>stat_qq()</code>). עם מדגם גדול, סטיות קטנות לא מזיקות למבחנים</li>
<li><strong>אי-תלות:</strong> אם הנתונים נאספו לאורך זמן, משרטטים את השאריות לפי סדר האיסוף</li>
</ul>
</section>
<section id="שאריות-מול-התפלגות-נורמלית" class="slide level2">
<h2>שאריות מול התפלגות נורמלית</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">augment</span>(fit4), <span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb36-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">colour =</span> nanas_pal[[<span class="st">"grey"</span>]], <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">colour =</span> nanas_pal[[<span class="st">"primary"</span>]]) <span class="sc">+</span></span>
<span id="cb36-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"השאריות קרובות לנורמליות"</span>,</span>
<span id="cb36-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"שאריות מתוקננות של fit4 מול הכמויות של N(0,1)"</span>,</span>
<span id="cb36-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Theoretical quantile"</span>, <span class="at">y =</span> <span class="st">"Standardised residual"</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="03-multiple-regression_files/figure-html/qq-plot-1.png" class="quarto-figure quarto-figure-center r-stretch" width="1200"></section>
<section id="מבחן-kolmogorovsmirnov-לשאריות" class="slide level2 smaller">
<h2>מבחן <span class="en">Kolmogorov–Smirnov</span> לשאריות</h2>
<p>גרף Q-Q הוא בדיקה בעין. אפשר גם לבדוק את הנורמליות במבחן, עם מבחן KS מההרצאה על שיטות א-פרמטריות:</p>
<p><span class="math display">\[
H_0: \text{השאריות המתוקננות מתפלגות } N(0, 1) \qquad D = \max_x \left| F_n(x) - \Phi(x) \right|
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">rstandard</span>(fit4), <span class="st">"pnorm"</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  rstandard(fit4)
D = 0.046, p-value = 0.7
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(D = 0.046 &lt; 0.086 \approx 1.36/\sqrt{250}\)</span>, ולכן <strong>לא דוחים</strong> את <span class="math inline">\(H_0\)</span>. אין עדות לסטייה מנורמליות</li>
<li><strong>הסתייגות:</strong> השאריות מחושבות מהמקדמים שאמדנו, ולכן ה-p-value רק בקירוב (כמו ב-KS עם פרמטרים אמודים). מבחן ייעודי לנורמליות הוא <code>shapiro.test()</code></li>
<li>עם מדגם גדול מאוד, KS ידחה גם סטייה זניחה. עם מדגם קטן, הוא לא יזהה גם סטייה גדולה. לכן מסתכלים <strong>גם</strong> על הגרף</li>
</ul>
</section>
<section id="מולטיקולינאריות-multicollinearity" class="slide level2 smaller">
<h2>מולטיקולינאריות (<span class="en">Multicollinearity</span>)</h2>
<p>מספר המסמכים מ-RAG קובע כמעט לגמרי את מספר הטוקנים בקלט: המתאם ביניהם הוא 0.94. מה קורה כשמכניסים את שניהם?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-hidden="true" tabindex="-1"></a>fit5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> rag_docs <span class="sc">+</span> output_tokens <span class="sc">*</span> model, <span class="at">data =</span> llm)</span>
<span id="cb39-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">fit4 =</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fit4))[<span class="st">"input_k"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],</span>
<span id="cb39-3"><a aria-hidden="true" tabindex="-1"></a>      <span class="at">fit5 =</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fit5))[<span class="st">"input_k"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Estimate Std. Error
fit4   0.2205    0.06423
fit5   0.4372    0.18807</code></pre>
</div>
</div>
<ul>
<li>שגיאת התקן של <code>input_k</code> גדלה פי 2.9. הרגרסיה לא יכולה להפריד בין שני משתנים שזזים יחד</li>
<li>המקדמים “לא יציבים”: שינוי קטן בנתונים מזיז אותם הרבה. <strong>החיזוי</strong> כמעט לא נפגע. <strong>הפרשנות</strong> נפגעת</li>
</ul>
<p><strong>מדד VIF</strong> (<span class="en">Variance Inflation Factor</span>): <span class="math inline">\(R_j^2\)</span> הוא ה-<span class="math inline">\(R^2\)</span> של רגרסיה של <span class="math inline">\(x_j\)</span> על כל שאר המשתנים המסבירים.</p>
<p><span class="math display">\[
VIF_j = \frac{1}{1 - R_j^2}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a aria-hidden="true" tabindex="-1"></a>r2_input <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(input_k <span class="sc">~</span> rag_docs <span class="sc">+</span> output_tokens <span class="sc">*</span> model, <span class="at">data =</span> llm))<span class="sc">$</span>r.squared</span>
<span id="cb41-2"><a aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> r2_input)    <span class="co"># VIF of input_k. Rule of thumb: above 5-10 is a problem</span></span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.672</code></pre>
</div>
</div>
</section></section>
<section>
<section id="בחירת-משתנים-variable-selection" class="title-slide slide level1 center">
<h1>בחירת משתנים (<span class="en">Variable selection</span>)</h1>

</section>
<section id="שלוש-גישות" class="slide level2 smaller">
<h2>שלוש גישות</h2>
<ul>
<li><strong>קדימה (<span class="en">Forward</span>):</strong> מתחילים ממודל בלי משתנים. בכל צעד מוסיפים את המשתנה שמשפר את הקריטריון הכי הרבה. עוצרים כשאף הוספה לא משפרת</li>
<li><strong>אחורה (<span class="en">Backward</span>):</strong> מתחילים מכל המשתנים. בכל צעד מוציאים את המשתנה שתורם הכי מעט, כל עוד ההוצאה לא פוגעת בקריטריון</li>
<li><strong>בצעדים (<span class="en">Stepwise</span>):</strong> כמו קדימה, אבל אחרי כל הוספה בודקים אם כדאי להוציא משתנה שכבר נכנס</li>
</ul>
<p><strong>קריטריונים נפוצים:</strong> <span class="math inline">\(R^2_{adj}\)</span>, ה-p-value של מבחן F חלקי, או <span class="en">AIC</span> (מדד שמאזן בין טיב ההתאמה למספר הפרמטרים. קטן יותר = טוב יותר)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-hidden="true" tabindex="-1"></a>fit_all  <span class="ot">&lt;-</span> <span class="fu">lm</span>(latency <span class="sc">~</span> input_k <span class="sc">+</span> rag_docs <span class="sc">+</span> hour <span class="sc">+</span> output_tokens <span class="sc">*</span> model, <span class="at">data =</span> llm)</span>
<span id="cb43-2"><a aria-hidden="true" tabindex="-1"></a>fit_step <span class="ot">&lt;-</span> <span class="fu">step</span>(fit_all, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">trace =</span> <span class="dv">0</span>)   <span class="co"># stepwise by AIC</span></span>
<span id="cb43-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">formula</span>(fit_step)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>latency ~ input_k + hour + output_tokens + model + output_tokens:model</code></pre>
</div>
</div>
</section>
<section id="מה-יכול-להשתבש-בבחירה-אוטומטית" class="slide level2 smaller">
<h2>מה יכול להשתבש בבחירה אוטומטית</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fit_step))[<span class="st">"hour"</span>, ]</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Estimate Std. Error    t value   Pr(&gt;|t|) 
 -0.014070   0.008184  -1.719055   0.086883 </code></pre>
</div>
</div>
<ul>
<li><code>hour</code> <strong>נשאר</strong> במודל, אף שבסימולציה לשעה אין שום השפעה על זמן התגובה. ה-p-value שלו אפילו קרוב ל-0.05</li>
<li>כשבודקים הרבה משתנים, חלקם ייראו מועילים במקרה. האלגוריתם בוחר בדיוק אותם</li>
<li><strong>ה-p-values אחרי בחירה אופטימיים מדי.</strong> המודל נבחר על סמך אותם נתונים שעליהם הוא נבדק</li>
<li><strong>עדיף:</strong> לבנות את המודל מתוך הבנה של המנגנון, ולבדוק אותו על נתונים שלא השתתפו בבנייתו. בפועל מחלקים את הנתונים לשני חלקים: <strong>סט אימון</strong> (<span class="en">train</span>) שעליו בוחרים ואומדים את המודל, ו<strong>סט בדיקה</strong> (<span class="en">test</span>) שעליו בודקים את החיזוי. בקורס בלמידת מכונה תלמדו על כך יותר</li>
</ul>
</section></section>
<section>
<section id="חיזוי-prediction" class="title-slide slide level1 center">
<h1>חיזוי (<span class="en">Prediction</span>)</h1>

</section>
<section id="רווח-סמך-מול-רווח-חיזוי" class="slide level2 smaller">
<h2>רווח סמך מול רווח חיזוי</h2>
<p>לנקודה חדשה <span class="math inline">\(\mathbf{x}_0 = (1, x_{01}, \dots, x_{0k})'\)</span>, החיזוי הוא <span class="math inline">\(\hat y_0 = \mathbf{x}_0'\hat{\boldsymbol\beta}\)</span>. יש שתי שאלות שונות:</p>
<ul>
<li><strong>רווח סמך</strong> (<span class="en">confidence interval</span>): איפה <strong>התוחלת</strong> <span class="math inline">\(E(Y \mid \mathbf{x}_0)\)</span>, זמן התגובה הממוצע של כל הקריאות האלה?</li>
<li><strong>רווח חיזוי</strong> (<span class="en">prediction interval</span>): איפה תיפול <strong>קריאה בודדת</strong> חדשה?</li>
</ul>
<p><span class="math display">\[
\text{CI:}\;\; \hat y_0 \pm t_{1-\alpha/2,\, n-k-1}\sqrt{\hat\sigma^2\, \mathbf{x}_0'(X'X)^{-1}\mathbf{x}_0}
\qquad
\text{PI:}\;\; \hat y_0 \pm t_{1-\alpha/2,\, n-k-1}\sqrt{\hat\sigma^2 \left(1 + \mathbf{x}_0'(X'X)^{-1}\mathbf{x}_0\right)}
\]</span></p>
<p>ה-1 הנוסף ברווח החיזוי הוא השונות של התצפית החדשה עצמה. גם עם אינסוף נתונים הוא לא נעלם.</p>
<p>ברגרסיה פשוטה, <span class="math inline">\(\mathbf{x}_0'(X'X)^{-1}\mathbf{x}_0 = \dfrac{1}{n} + \dfrac{(x_0 - \bar x)^2}{S_{xx}}\)</span>: הרווחים צרים ביותר ב-<span class="math inline">\(\bar x\)</span> ומתרחבים ככל שמתרחקים ממנו.</p>
</section>
<section id="חזרה-לשאלה-כמה-זמן-תיקח-הקריאה" class="slide level2">
<h2>חזרה לשאלה: כמה זמן תיקח הקריאה?</h2>
<p>2,000 טוקנים בקלט, 500 בפלט, מודל השפה הגדול:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a aria-hidden="true" tabindex="-1"></a>new_call <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">input_k =</span> <span class="dv">2</span>, <span class="at">output_tokens =</span> <span class="dv">500</span>, <span class="at">model =</span> <span class="st">"large"</span>)</span>
<span id="cb47-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">confidence =</span> <span class="fu">predict</span>(fit4, new_call, <span class="at">interval =</span> <span class="st">"confidence"</span>)[<span class="dv">1</span>, ],</span>
<span id="cb47-3"><a aria-hidden="true" tabindex="-1"></a>      <span class="at">prediction =</span> <span class="fu">predict</span>(fit4, new_call, <span class="at">interval =</span> <span class="st">"prediction"</span>)[<span class="dv">1</span>, ])</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            fit   lwr   upr
confidence 16.2 15.92 16.49
prediction 16.2 14.35 18.06</code></pre>
</div>
</div>
<ul>
<li><strong>בממוצע</strong>, קריאות כאלה לוקחות בין 15.9 ל-16.5 שניות</li>
<li><strong>קריאה בודדת</strong> תיקח, ב-95% מהמקרים, בין 14.3 ל-18.1 שניות. זה המספר שרלוונטי להתחייבות לזמן תגובה (<span class="en">SLA</span>)</li>
</ul>
</section>
<section id="איך-זה-נראה" class="slide level2">
<h2>איך זה נראה</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a aria-hidden="true" tabindex="-1"></a>grid_cpu <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">load =</span> <span class="fu">seq</span>(<span class="dv">8</span>, <span class="dv">19</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb49-2"><a aria-hidden="true" tabindex="-1"></a>bands <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(grid_cpu,</span>
<span id="cb49-3"><a aria-hidden="true" tabindex="-1"></a>                   <span class="fu">predict</span>(fit_cpu, grid_cpu, <span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>(),</span>
<span id="cb49-4"><a aria-hidden="true" tabindex="-1"></a>                   <span class="fu">predict</span>(fit_cpu, grid_cpu, <span class="at">interval =</span> <span class="st">"prediction"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb49-5"><a aria-hidden="true" tabindex="-1"></a>                     <span class="fu">select</span>(<span class="at">pi_lwr =</span> lwr, <span class="at">pi_upr =</span> upr))</span>
<span id="cb49-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bands, <span class="fu">aes</span>(load)) <span class="sc">+</span></span>
<span id="cb49-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> pi_lwr, <span class="at">ymax =</span> pi_upr), <span class="at">fill =</span> nanas_pal[[<span class="st">"sky"</span>]], <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb49-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr), <span class="at">fill =</span> nanas_pal[[<span class="st">"primary"</span>]], <span class="at">alpha =</span> <span class="fl">0.35</span>) <span class="sc">+</span></span>
<span id="cb49-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> fit), <span class="at">colour =</span> nanas_pal[[<span class="st">"primary"</span>]], <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb49-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(load, util), <span class="at">data =</span> cpu, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb49-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"רווח החיזוי רחב יותר מרווח הסמך, ושניהם מתרחבים בקצוות"</span>,</span>
<span id="cb49-13"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"דוגמת המעבד · כהה: רווח סמך 95% לתוחלת · בהיר: רווח חיזוי 95% לתצפית בודדת"</span>,</span>
<span id="cb49-14"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Load (k requests / min)"</span>, <span class="at">y =</span> <span class="st">"CPU utilisation (%)"</span>)</span></code></pre></div><button title="העתק ללוח" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section><section id="איך-זה-נראה-output" class="slide level2 output-location-slide"><h2>איך זה נראה</h2><div class="cell output-location-slide" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="03-multiple-regression_files/figure-html/ci-pi-plot-1.png" class="quarto-figure quarto-figure-center" width="1200"></p>
</figure>
</div>
</div>
</div></section></section>
<section>
<section id="מה-יכול-להשתבש" class="title-slide slide level1 center">
<h1>מה יכול להשתבש</h1>

</section>
<section id="חמש-מלכודות" class="slide level2 smaller">
<h2>חמש מלכודות</h2>
<ol type="1">
<li><strong>אקסטרפולציה:</strong> לפי מודל המעבד, ניצולת של 80% תגיע בעומס של כ-57 אלף בקשות בדקה. אבל מדדנו רק בין 10 ל-17. מעבדים בעומס גבוה מתנהגים אחרת (תורים, <span class="en">throttling</span>), והמודל לא יודע על זה כלום</li>
<li><strong>מתאם אינו סיבתיות:</strong> נתוני הלוגים הם תצפיתיים. אם משתמשים בוחרים במודל השפה הגדול למשימות קשות, ייתכן שגם משהו אחר במשימות האלה מאט אותן. כדי לדעת בוודאות, צריך ניסוי (על כך בהרצאה על תכנון ניסויים)</li>
<li><strong><span class="math inline">\(R^2\)</span> גבוה אינו הוכחה:</strong> הוא תמיד עולה כשמוסיפים משתנים. משווים מודלים לפי <span class="math inline">\(R^2_{adj}\)</span>, מבחן F חלקי, או ביצועים על נתונים חדשים</li>
<li><strong>מולטיקולינאריות:</strong> מקדמים לא יציבים ושגיאות תקן גדולות, אף שהחיזוי בסדר</li>
<li><strong>מודל שגוי מסתיר אפקטים:</strong> <code>input_k</code> נראה חסר השפעה עד שהוספנו את גודל מודל השפה והאינטראקציה. <strong>תמיד</strong> מסתכלים על השאריות</li>
</ol>
</section></section>
<section>
<section id="סיכום" class="title-slide slide level1 center">
<h1>סיכום</h1>

</section>
<section id="מה-לקחת-מההרצאה" class="slide level2 smaller">
<h2>מה לקחת מההרצאה</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>השאלה</th>
<th>הכלי</th>
<th>ב-R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>מה הקשר בין <span class="math inline">\(Y\)</span> לכל משתנה, כשהשאר קבועים?</td>
<td><span class="math inline">\(\hat{\boldsymbol\beta} = (X'X)^{-1}X'\mathbf{y}\)</span></td>
<td><code>lm(y ~ x1 + x2)</code>, <code>summary()</code></td>
</tr>
<tr class="even">
<td>האם משתנה בודד תורם?</td>
<td>מבחן t, <span class="math inline">\(t_{n-k-1}\)</span></td>
<td><code>summary()</code></td>
</tr>
<tr class="odd">
<td>האם המודל כולו מסביר משהו?</td>
<td>מבחן F, <span class="math inline">\(F_{k,\,n-k-1}\)</span></td>
<td>שורה אחרונה ב-<code>summary()</code></td>
</tr>
<tr class="even">
<td>האם קבוצת משתנים תורמת?</td>
<td>מבחן F חלקי, <span class="math inline">\(F_{q,\,n-k-1}\)</span></td>
<td><code>anova(reduced, full)</code></td>
</tr>
<tr class="odd">
<td>משתנה קטגורי עם <span class="math inline">\(m\)</span> רמות</td>
<td><span class="math inline">\(m - 1\)</span> משתני דמה</td>
<td><code>factor</code></td>
</tr>
<tr class="even">
<td>האם השיפוע תלוי בקבוצה?</td>
<td>אינטראקציה</td>
<td><code>x * group</code></td>
</tr>
<tr class="odd">
<td>האם ההנחות מתקיימות?</td>
<td>שאריות, Q-Q, VIF</td>
<td><code>augment()</code>, <code>stat_qq()</code></td>
</tr>
<tr class="even">
<td>מה צפוי לתצפית חדשה?</td>
<td>רווח סמך / חיזוי</td>
<td><code>predict(interval = )</code></td>
</tr>
</tbody>
</table>
<ul>
<li>כל מקדם מתפרש <strong>בהינתן שאר המשתנים במודל</strong>. כשמשנים את המודל, משתנה גם הפרשנות</li>
<li>את המודל בונים מתוך הבנה של המנגנון. אלגוריתם בחירה הוא כלי עזר, לא תחליף</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ניתוח נתונים סטטיסטי · תשפ״ז</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: true,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "הועתק!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "הועתק!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/adisarid\.github\.io\/nanas-tau\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>