{
  "hash": "66b6d122b923c52472e12489060b8937",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1. שיטות א-פרמטריות\"\nsubtitle: \"ניתוח נתונים סטטיסטי · הרצאה 1\"\nauthor: \"ד״ר עדי שריד\"\ndate: last-modified\nformat:\n  revealjs:\n    output-file: 01-nonparametric-slides.html\n---\n\n\n\n## על מה נדבר היום\n\n- תזכורת קצרה: מהי בדיקת השערות\n- מתי ההנחות של מבחן פרמטרי לא מתקיימות, ולמה זה משנה\n- **מבחן הסימן**: השערות על החציון, גם למדגמים מזווגים\n- **מבחן הדירוגים המסומנים** ([Wilcoxon signed-rank]{.en})\n- **מבחן סכום הדירוגים** ([Wilcoxon rank-sum / Mann–Whitney]{.en})\n- **טיב התאמה**: מבחן חי-בריבוע ומבחן [Kolmogorov–Smirnov]{.en}\n- **מתאם על דירוגים**: [Spearman]{.en} ו-[Kendall]{.en}\n\n# תזכורת: בדיקת השערות\n\n## השאלה: האם הזכרים כבדים יותר?\n\n- נתוני [Palmer Penguins]{.en}: מדידות של פינגווינים בתחנת המחקר פאלמר באנטארקטיקה\n- נתמקד במין אחד, [Gentoo]{.en}, ובמשתנה אחד: **משקל הגוף** (גרם)\n- **השאלה:** האם יש הבדל במשקל הממוצע בין זכרים לנקבות?\n- הנתונים מגיעים עם R (מגרסה 4.5), בלי חבילה נוספת\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngentoo <- penguins |> filter(species == \"Gentoo\", !is.na(sex))\ngentoo |> summarise(n = n(), mean = mean(body_mass), sd = sd(body_mass), .by = sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sex  n mean    sd\n1 female 58 4680 281.6\n2   male 61 5485 313.2\n```\n\n\n:::\n:::\n\n\n## התפלגות המשקל\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nggplot(gentoo, aes(body_mass)) +\n  geom_histogram(binwidth = 100, fill = nanas_pal[[\"grey\"]]) +\n  labs(title = \"משקל הגוף של פינגווינים מסוג Gentoo\",\n       subtitle = \"119 פרטים, זכרים ונקבות יחד\",\n       x = \"Body mass (g)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/penguins-hist-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nההתפלגות רחבה, ונראה שיש בה שתי \"גבעות\". זה רמז שמסתתר כאן משתנה נוסף.\n:::\n\n## המשקל לפי מין\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nsex_means <- gentoo |> summarise(mean = mean(body_mass), .by = sex)\n\nggplot(gentoo, aes(body_mass, fill = sex)) +\n  geom_histogram(binwidth = 100, alpha = 0.6, position = \"identity\") +\n  geom_vline(aes(xintercept = mean, colour = sex), data = sex_means,\n             linetype = \"dashed\", linewidth = 0.9, show.legend = FALSE) +\n  scale_fill_manual(values = c(female = nanas_pal[[\"accent\"]], male = nanas_pal[[\"primary\"]])) +\n  scale_colour_manual(values = c(female = nanas_pal[[\"accent\"]], male = nanas_pal[[\"primary\"]])) +\n  labs(title = \"הזכרים כבדים בכ-800 גרם בממוצע\",\n       subtitle = \"הקווים המקווקווים: הממוצע בכל קבוצה\",\n       x = \"Body mass (g)\", y = \"Count\", fill = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/penguins-hist-sex-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nשתי ה\"גבעות\" הן שתי הקבוצות. ההבדל נראה גדול, אבל ההיסטוגרמות חופפות בחלקן. השאלה הסטטיסטית היא האם הבדל כזה יכול לנבוע ממקריות הדגימה בלבד.\n:::\n\n## מבחן t לשני מדגמים {.smaller}\n\n$$\nH_0: \\mu_F = \\mu_M \\qquad H_1: \\mu_F \\neq \\mu_M\n$$\n\n$$\nt = \\frac{\\bar{x}_F - \\bar{x}_M}{\\sqrt{\\dfrac{s_F^2}{n_F} + \\dfrac{s_M^2}{n_M}}}\n= \\frac{4679.7 - 5484.8}{\\sqrt{\\dfrac{281.6^2}{58} + \\dfrac{313.2^2}{61}}}\n= \\frac{-805.1}{54.5} \\approx -14.76\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(body_mass ~ sex, data = gentoo) |>\n  print(digits = 6)  # a little more precision than the course default\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body_mass by sex\nt = -14.76, df = 116.6, p-value <2e-16\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -913.113 -697.076\nsample estimates:\nmean in group female   mean in group male \n             4679.74              5484.84 \n```\n\n\n:::\n:::\n\n\n## איך קוראים את הפלט\n\n- **`t = -14.76`**: ההפרש בין הממוצעים הוא כ-15 שגיאות תקן. הסימן שלילי כי R מחסר זכרים מנקבות\n- **`df = 116.6`**: [Welch]{.en} לא מניח שוויון שונויות, ולכן דרגות החופש לא שלמות\n- **`p-value < 2e-16`**: אם $H_0$ נכונה, הסיכוי לראות הפרש קיצוני כזה כמעט אפס. **דוחים** את $H_0$\n- **רווח הסמך (95%)**: הנקבות קלות מהזכרים ב-697 עד 913 גרם. הערך 0 לא נמצא ברווח\n- **ההנחות:** תצפיות בלתי תלויות, והתפלגות נורמלית בכל קבוצה (או מדגם גדול)\n\n::: notes\nלהזכיר: p-value איננו ההסתברות ש-H0 נכונה. זו ההסתברות לנתונים קיצוניים כאלה או יותר, בהינתן ש-H0 נכונה.\n:::\n\n::: {.content-hidden when-format=\"revealjs\"}\nכאן ההנחות סבירות: ההיסטוגרמות בכל קבוצה נראות פעמוניות, ויש כ-60 פרטים בכל קבוצה. בשאר ההרצאה נשאל מה עושים כשההנחה על ההתפלגות **לא** מתקיימת, למשל כשיש ערכים קיצוניים או כשהמדגם קטן.\n:::\n\n# למה צריך שיטות א-פרמטריות?\n\n## הרעיון\n\n- שיטות פרמטריות (מבחן t, ANOVA) מניחות **התפלגות ידועה** של תגובת המערכת, בדרך כלל נורמלית\n- שיטות א-פרמטריות מסתפקות ב**מידע חלקי** על ההתפלגות\n- הן נשענות פחות על הערכים עצמם ויותר על **הסדר שלהם (הדירוג)**\n- אין שיטה אחת לכל דבר: לכל השערה יש מבחן ייעודי\n\n::: {.content-hidden when-format=\"revealjs\"}\nבפועל, נתונים \"לא נורמליים\" הם הכלל ולא החריג. זמני תגובה של מערכות, הכנסות, זמני המתנה בתור, ציוני שביעות רצון בסולם 1–5 ודירוגים בתחרות הם כולם מוטים, בדידים או מלאים בערכים חריגים. כשהמדגם קטן, משפט הגבול המרכזי לא מספיק כדי להציל אותנו.\n:::\n\n## כשהתוחלת בכלל לא קיימת\n\nדוגמה:\n\n$$\nf(x) = \\dfrac{1}{(1+x)^2}, \\quad x \\in [0, \\infty)\n$$\n\n$$\n\\mu = \\int_0^\\infty \\frac{x}{(1+x)^2}\\,dx = \\infty\n$$\n\n$$\nF(a) = 1 - \\frac{1}{1+a} = 0.5 \\;\\Rightarrow\\; \\tilde{\\mu} = 1\n$$\n\n- אין טעם לבדוק השערות על התוחלת, כי היא אינסופית\n- **החציון** מוגדר היטב, ואפשר לבדוק השערות עליו\n\n## סימולציה: ממוצע מול חציון\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\n# F(x) = 1 - 1/(1+x)  =>  x = 1/(1-u) - 1\nn <- 20000\nheavy <- tibble(\n  i = 1:n,\n  x = 1 / (1 - runif(n)) - 1\n) |>\n  mutate(\n    `ממוצע מצטבר` = cummean(x),\n    `חציון מצטבר` = map_dbl(i, \\(k) median(x[seq_len(k)]))\n  ) |>\n  filter(i %% 20 == 0) |>\n  pivot_longer(c(`ממוצע מצטבר`, `חציון מצטבר`), names_to = \"stat\")\n\nggplot(heavy, aes(i, value, colour = stat)) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"grey50\") +\n  geom_line(linewidth = 0.8) +\n  scale_x_log10(labels = label_comma()) +\n  scale_colour_manual(values = c(nanas_pal[[\"accent\"]], nanas_pal[[\"primary\"]])) +\n  labs(title = \"החציון מתכנס ל-1, הממוצע ממשיך לטפס\",\n       subtitle = \"דגימות מהתפלגות שבה התוחלת אינסופית\",\n       x = \"Sample size (log scale)\", y = NULL, colour = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/running-mean-median-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nהממוצע \"קופץ\" בכל פעם שמגיעה תצפית קיצונית, ולעולם לא מתייצב. החציון מתייצב מהר מאוד סביב 1. זו האינטואיציה לכל ההרצאה: סטטיסטיים שמבוססים על סדר ודירוג **עמידים** לערכים קיצוניים.\n:::\n\n## מפת דרכים {.smaller}\n\n| השאלה | השיטה הפרמטרית | השיטה הא-פרמטרית |\n|---|---|---|\n| מרכז ההתפלגות | מבחן t / Z על התוחלת | מבחן הסימן ([Sign test]{.en}), מבחן הדירוגים המסומנים ([Wilcoxon signed-rank]{.en}) |\n| שני מדגמים מזווגים | מבחן t מזווג | מבחן הסימן / [Wilcoxon signed-rank]{.en} על ההפרשים |\n| שתי אוכלוסיות בלתי תלויות | מבחן t לשני מדגמים | מבחן סכום הדירוגים ([Mann–Whitney]{.en}) |\n| התאמה להתפלגות נתונה | מבחן חי-בריבוע לטיב התאמה ([Goodness-of-fit]{.en}) | מבחן [Kolmogorov–Smirnov]{.en} |\n| השוואה בין שתי התפלגויות | | [Kolmogorov–Smirnov]{.en} לשני מדגמים |\n| מתאם בין שני משתנים | מתאם פירסון | [Spearman's ρ]{.en}, [Kendall's τ]{.en} |\n\n: {tbl-colwidths=\"[27,28,45]\"}\n\n# מבחן הסימן\n\n## השערות על החציון\n\n$$\nH_0: \\tilde{\\mu} = z \\qquad H_1: \\tilde{\\mu} \\neq z\n$$\n\n- תחת $H_0$, כל הפרש $x_i - z$ חיובי או שלילי בהסתברות $0.5$\n- תצפיות ששוות בדיוק ל-$z$ (הפרש $0$) **משמיטים**, ו-$n$ הוא מספר התצפיות שנשארו\n- $r^+$: מספר ההפרשים החיוביים\n- סטטיסטי המבחן: $r = \\min(r^+,\\; n - r^+)$\n- תחת $H_0$ נצפה ש-$r$ יהיה קרוב ל-$n/2$, וערך קטן מעיד נגד $H_0$\n\n$$\nr^+ \\sim \\text{Binomial}(n, 0.5)\n\\qquad\nP(r \\le y) = 2\\,P(r^+ \\le y), \\quad y < n/2\n$$\n\n## הערך הקריטי\n\nהערך הקריטי $R^*_\\alpha$ הוא הערך הגדול ביותר שמקיים\n\n$$\nP(r \\le R^*_\\alpha) = 2 \\sum_{y=0}^{R^*_\\alpha} \\binom{n}{y}\\left(\\frac{1}{2}\\right)^n \\le \\alpha\n$$\n\n**כלל ההכרעה:** אם $r_0 \\le R^*_\\alpha$, דוחים את $H_0$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Critical value of the sign test: largest r with 2 * P(Bin(n, 0.5) <= r) <= alpha\nsign_critical <- function(n, alpha) {\n  max(which(2 * pbinom(0:n, n, 0.5) <= alpha)) - 1\n}\nsapply(c(`0.01` = 0.01, `0.05` = 0.05, `0.10` = 0.10), \\(a) sign_critical(20, a))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.01 0.05 0.10 \n   3    5    5 \n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nבבחינה הערך הקריטי נתון בטבלה. ב-R מחשבים אותו בשורה אחת, או מוותרים עליו ומסתכלים ישר על ה-p-value.\n:::\n\n## דוגמה: זמני תגובה של API\n\nה-SLA של שירות קובע שהחציון של זמן התגובה הוא **200 ms**. נדגמו 20 בקשות:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napi <- read_csv(file.path(data_dir, \"api_latency.csv\"), show_col_types = FALSE)\napi |> mutate(diff = latency_ms - 200, sign = if_else(diff > 0, \"+\", \"-\")) |>\n  count(sign)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sign      n\n  <chr> <int>\n1 +        15\n2 -         5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nggplot(api, aes(latency_ms, 0, colour = latency_ms > 200)) +\n  geom_vline(xintercept = 200, linetype = \"dashed\", colour = \"grey40\") +\n  geom_point(size = 4, alpha = 0.8, position = position_jitter(height = 0.02, seed = 1)) +\n  scale_colour_manual(values = c(`FALSE` = nanas_pal[[\"accent\"]], `TRUE` = nanas_pal[[\"primary\"]]),\n                      labels = c(\"מתחת ל-200\", \"מעל 200\")) +\n  scale_y_continuous(NULL, breaks = NULL, limits = c(-0.1, 0.1)) +\n  labs(title = \"15 מתוך 20 בקשות מעל 200 ms\", x = \"Latency (ms)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/api-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## מבחן הסימן: חישוב\n\n- $r^+ = 15 \\;\\Rightarrow\\; r_0 = \\min(15, 5) = 5$\n- ב-$\\alpha = 0.01$: $R^*_{0.01} = 3$, ו-$5 > 3$, ולכן **לא דוחים** את $H_0$\n- ב-$\\alpha = 0.05$: $R^*_{0.05} = 5$, ו-$5 \\le 5$, ולכן **דוחים**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbinom.test(sum(api$latency_ms > 200), n = nrow(api), p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  sum(api$latency_ms > 200) and nrow(api)\nnumber of successes = 15, number of trials = 20, p-value = 0.04\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5090 0.9134\nsample estimates:\nprobability of success \n                  0.75 \n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\n**איך קוראים את הפלט:** `number of successes = 15` הוא $r^+$, ו-`p-value = 0.04139` הוא $2 \\cdot P(r^+ \\le 5)$. המסקנה תלויה ברמת המובהקות שנקבעה **מראש**: ב-1% אין מספיק ראיות, וב-5% יש.\n:::\n\n## דוגמה: חציון הציונים במועד ב׳ {.smaller}\n\nמרצה טוען שחציון הציונים במועד ב׳ שלו הוא 80. ניגשו 11 סטודנטים. האם הטענה נכונה ב-$\\alpha = 0.1$?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrades <- read_csv(file.path(data_dir, \"exam_grades.csv\"), show_col_types = FALSE)\ngrades$grade\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 79 75 85 95 70 60 65 75 74 89 72\n```\n\n\n:::\n\n```{.r .cell-code}\nbinom.test(sum(grades$grade > 80), n = nrow(grades))$p.value  # sign test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2266\n```\n\n\n:::\n:::\n\n\n- $r^+ = 3$, $r_0 = 3 > R^*_{0.1,11} = 2$, ולכן טענת המרצה **אינה נדחית**\n- גם מבחן t לתוחלת (בהנחת נורמליות) לא דוחה את $H_0$\n\n::: {.fragment}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(grades$grade, mu = 80) |> print(digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  grades$grade\nt = -1.204, df = 10, p-value = 0.256\nalternative hypothesis: true mean is not equal to 80\n95 percent confidence interval:\n 69.3750 83.1704\nsample estimates:\nmean of x \n  76.2727 \n```\n\n\n:::\n:::\n\n:::\n\n## מבחן הסימן למדגמים מזווגים {.smaller}\n\nכשהתצפיות **מזווגות**, מריצים את מבחן הסימן על ההפרשים $d_i = x_i - y_i$, עם $H_0: \\tilde{\\mu}_d = 0$.\n\n**דוגמה:** צוות מוצר שוקל להחליף את [Sonnet 5.5]{.en} ב-[Opus 5.5]{.en}, היקר יותר, למשימות תיוג. שני המודלים תייגו את אותן 11 משימות. **האם Opus טועה פחות?** בטבלה: שיעור השגיאות (%) בכל משימה. $d_i$ = Opus פחות Sonnet. (נתונים מדומים)\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nllm_err <- read_csv(file.path(data_dir, \"llm_labelling_errors.csv\"), show_col_types = FALSE)\nllm_err |>\n  mutate(sign = if_else(opus > sonnet, \"+\", \"-\")) |>\n  select(task = task_he, sonnet, opus, sign) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|task                | sonnet| opus|sign |\n|:-------------------|------:|----:|:----|\n|ניתוב פניות שירות   |    8.4|  6.9|-    |\n|סנטימנט בביקורות    |    4.1|  3.6|-    |\n|זיהוי ספאם          |    2.3|  2.1|-    |\n|זיהוי כוונה בצ׳אט   |   11.2|  9.0|-    |\n|זיהוי תוכן פוגעני   |    6.5| 12.4|+    |\n|שדות בחשבוניות      |    9.8|  8.1|-    |\n|זיהוי שפה           |    1.4|  0.6|-    |\n|תעדוף פניות רפואיות |   14.7| 11.6|-    |\n|סיווג סעיפים בחוזים |   13.0| 10.4|-    |\n|קטגוריית מוצר       |    7.2|  6.0|-    |\n|זיהוי סרקזם         |   15.3| 22.1|+    |\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nלמה **מזווג**? יש משימות קשות לכל מודל (סרקזם, תעדוף רפואי) ויש קלות (זיהוי שפה, ספאם). ההבדל בין המשימות גדול בהרבה מההבדל בין המודלים, ולכן משווים את שני המודלים **בתוך** כל משימה.\n:::\n\n## Sonnet מול Opus: התוצאה\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_plus <- sum(llm_err$opus > llm_err$sonnet)\nbinom.test(n_plus, n = nrow(llm_err)) |> print(digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  n_plus and nrow(llm_err)\nnumber of successes = 2, number of trials = 11, p-value = 0.0654\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.0228312 0.5177559\nsample estimates:\nprobability of success \n              0.181818 \n```\n\n\n:::\n:::\n\n\n- $r^+ = 2$, ו-$p = 0.065 < 0.1$, ולכן **דוחים** $H_0$: חציון ההפרשים אינו 0\n- Opus טועה פחות ב-9 מתוך 11 המשימות\n\n# מבחן הדירוגים המסומנים\n\n## הרחבה של מבחן הסימן\n\n- מתבסס לא רק על **הסימן** של ההפרשים אלא גם על **גודלם**\n- מתאים להתפלגויות **רציפות וסימטריות**, שבהן התוחלת והחציון שווים\n- לרוב חזק יותר ממבחן הסימן\n- אפשר להפעיל גם על הפרשים של מדגמים מזווגים\n\n## שלבי המבחן {.smaller}\n\n\n1. משמיטים הפרשים ששווים ל-$0$ ומעדכנים את $n$. מדרגים את $|x_i - z|$ בסדר עולה. במקרה של שוויון, כל אחד מקבל את ממוצע הדרגות\n2. מצמידים לכל דרגה את הסימן של ההפרש שלה\n3. $R^+$ הוא סכום הדרגות החיוביות ו-$R^-$ סכום הדרגות השליליות, וסטטיסטי המבחן הוא $R = \\min(R^+, R^-)$\n4. דוחים את $H_0$ אם $R \\le R^*_{\\alpha,n}$ (טבלה), או לפי קירוב נורמלי:\n\n$$\nE(R^+) = \\frac{n(n+1)}{4} \\qquad V(R^+) = \\frac{n(n+1)(2n+1)}{24}\n$$\n\n## חזרה לזמני התגובה\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigned <- api |>\n  mutate(diff = latency_ms - 200,\n         rank = rank(abs(diff)),\n         signed_rank = sign(diff) * rank) |>\n  arrange(rank)\n\nsigned |> summarise(R_plus  = sum(rank[diff > 0]),\n                    R_minus = sum(rank[diff < 0]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  R_plus R_minus\n   <dbl>   <dbl>\n1   156.    53.5\n```\n\n\n:::\n:::\n\n\n$$\nR = \\min(156.5,\\; 53.5) = 53.5 < 60 = R^*_{0.1,\\,20}\n$$\n\nולכן **דוחים** את $H_0$ ב-$\\alpha = 0.1$.\n\n::: {.content-hidden when-format=\"revealjs\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigned |> select(request, diff, signed_rank) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| request| diff| signed_rank|\n|-------:|----:|-----------:|\n|      16|    5|         1.0|\n|       4|    6|         2.0|\n|      20|   11|         3.0|\n|       1|   15|         4.0|\n|      11|   16|         5.0|\n|       5|   20|         6.5|\n|      18|   20|         6.5|\n|       7|  -22|        -8.5|\n|      13|  -22|        -8.5|\n|      15|  -24|       -10.0|\n|      10|   25|        11.0|\n|       6|  -30|       -12.0|\n|       3|   31|        13.0|\n|       2|  -33|       -14.5|\n|      14|   33|        14.5|\n|       9|   35|        16.0|\n|      12|   40|        17.0|\n|      17|   41|        18.0|\n|       8|   57|        19.0|\n|      19|   65|        20.0|\n\n\n:::\n:::\n\n:::\n\n## בדיקה ב-R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwilcox.test(api$latency_ms, mu = 200, exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  api$latency_ms\nV = 156, p-value = 0.06\nalternative hypothesis: true location is not equal to 200\n```\n\n\n:::\n:::\n\n\n- `V` ב-R הוא $R^+$ (156.5), לא $\\min(R^+, R^-)$\n- `exact = FALSE`: יש דרגות זהות, ולכן R משתמש בקירוב הנורמלי\n\n## כשהמבחנים לא מסכימים\n\nנחזור ל-Sonnet מול Opus:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(sign        = binom.test(n_plus, nrow(llm_err))$p.value,\n  signed_rank = wilcox.test(llm_err$opus, llm_err$sonnet, paired = TRUE)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       sign signed_rank \n    0.06543     0.32031 \n```\n\n\n:::\n:::\n\n\n- ב-$\\alpha = 0.1$ מבחן הסימן דוחה ומבחן הדירוגים המסומנים לא\n- **אם ההתפלגות סימטרית**, מבחן הדירוגים המסומנים מדויק יותר והוא שקובע\n- **אם אי אפשר להניח סימטריה**, מבחן הסימן קובע\n\n::: {.content-hidden when-format=\"revealjs\"}\nכדאי לשים לב ממה נובע הפער. Opus מנצח ב-9 משימות, אבל בהפרשים קטנים (0.2 עד 3.1 נקודות אחוז). בשתי המשימות שבהן Sonnet עדיף, זיהוי תוכן פוגעני וזיהוי סרקזם, הפערים גדולים: 5.9 ו-6.8 נקודות אחוז. ההפרשים רחוקים מסימטריה, ולכן כאן מבחן הסימן הוא המתאים. ובכל זאת, למוצר יש מסקנה מעשית: לפני שמחליפים מודל, בודקים איפה הוא **נכשל**, ולא רק כמה פעמים הוא ניצח. ממוצע ההפרשים כאן הוא 0.1 בלבד, ומבחן t מזווג לא היה מוצא שום הבדל. מבחן הסימן סופר רק כמה פעמים כל שיטה ניצחה, ומבחן הדירוגים המסומנים מתחשב גם בגודל הניצחון. השאלה איזה מבחן לבחור היא שאלה על ההנחות, ולא על איזה מבחן נותן את התשובה שרצינו. ואת ההחלטה מקבלים **לפני** שמסתכלים על התוצאה.\n:::\n\n# מבחן סכום הדירוגים\n\n## שתי אוכלוסיות בלתי תלויות {.smaller}\n\n- $n$ תצפיות מאוכלוסייה א׳ ו-$m$ תצפיות מאוכלוסייה ב׳, עם $m \\le n$ ו-$N = n + m$\n- $H_0: F_1(x) = F_2(x)$ מול $H_1: F_1(x) \\neq F_2(x)$\n- **השיטה** ([Wilcoxon rank-sum]{.en}): מאחדים את כל התצפיות לרשימה אחת וממיינים\n- **סטטיסטי המבחן** $T$: סכום הדרגות של התצפיות מהמדגם **הקטן**\n\n$$\nE(T) = \\frac{m(n+m+1)}{2} \\qquad V(T) = \\frac{mn(n+m+1)}{12}\n$$\n\nדוחים את $H_0$ אם $\\left|\\frac{T - E(T)}{\\sigma_T}\\right| > Z_{1-\\alpha/2}$\n\n::: {.content-hidden when-format=\"revealjs\"}\n**מאיפה מגיעה התוחלת?** תחת $H_0$ כל תצפית יכולה לתפוס כל מקום ברשימה המאוחדת באותה הסתברות, ולכן $E(R_i) = \\frac{N+1}{2}$ לכל תצפית. סכום של $m$ תצפיות נותן $E(T) = m \\cdot \\frac{N+1}{2}$. חישוב השונות דורש גם את השונות המשותפת בין הדרגות (הן לא בלתי תלויות, כי שתי תצפיות לא יכולות לקבל אותה דרגה), והתוצאה היא הנוסחה שלמעלה.\n:::\n\n## דוגמה: שיפור בתהליך ייצור\n\nשיפור טכנולוגי בתהליך הייצור לא שינה את **צורת** ההתפלגות של התפוקה היומית, אבל הזיז אותה כלפי מעלה. **האם התפוקה עלתה ב-3 יחידות ביום?** ($\\alpha = 0.05$)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprod <- read_csv(file.path(data_dir, \"production_output.csv\"), show_col_types = FALSE)\nprod |> group_by(period) |> summarise(units = paste(units, collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  period units                       \n  <chr>  <chr>                       \n1 after  7.7, 8.1, 8.3, 8.6, 8.9     \n2 before 3.9, 4.3, 4.4, 4.6, 4.9, 5.8\n```\n\n\n:::\n:::\n\n\n**הטריק:** מורידים 3 מהתצפיות שאחרי השיפור. אם התפוקה עלתה ב-3 בדיוק, שני המדגמים מגיעים מאותה התפלגות.\n\n## דירוג הרשימה המאוחדת\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nprod_shift <- prod |>\n  mutate(adj = if_else(period == \"after\", units - 3, units),\n         rank = rank(adj))\n\nggplot(prod_shift, aes(adj, 0, colour = period, label = rank)) +\n  geom_point(size = 9, alpha = 0.85) +\n  geom_text(colour = \"white\", fontface = \"bold\", size = 4) +\n  scale_colour_manual(values = c(after = nanas_pal[[\"accent\"]], before = nanas_pal[[\"primary\"]]),\n                      labels = c(after = \"אחרי (פחות 3)\", before = \"לפני\")) +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"הדרגות של המדגם המאוחד\", x = \"Daily output (units)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/production-ranks-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n$$\nT_0 = 5 + 7 + 8 + 9 + 11 = 40, \\quad\nE(T) = \\tfrac{5 \\cdot 12}{2} = 30, \\quad\nV(T) = \\tfrac{5 \\cdot 6 \\cdot 12}{12} = 30\n$$\n\n$$\n\\left|\\frac{40 - 30}{\\sqrt{30}}\\right| = 1.82 < 1.96\n$$\n\nולכן **לא דוחים** $H_0$: הנתונים מתיישבים עם שיפור של 3 יחידות ביום.\n\n## אותו מבחן ב-R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nafter  <- prod$units[prod$period == \"after\"]\nbefore <- prod$units[prod$period == \"before\"]\nwilcox.test(after, before, mu = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  after and before\nW = 25, p-value = 0.08\nalternative hypothesis: true location shift is not equal to 3\n```\n\n\n:::\n:::\n\n\n- ב-R הסטטיסטי `W` הוא $T - \\frac{m(m+1)}{2} = 40 - 15 = 25$ (סטטיסטי [Mann–Whitney U]{.en})\n- `mu = 3` בודק הזזה של 3 יחידות, בלי לחסר ידנית\n- R מחשב p-value **מדויק** (0.082) ולא את הקירוב הנורמלי, אבל המסקנה זהה\n\n# טיב התאמה\n\n## תזכורת: מבחן חי-בריבוע לטיב התאמה {.smaller}\n\n$H_0$: ההסתברויות של $k$ הקטגוריות הן $p_1, \\dots, p_k$. $O_i$ הוא המספר שנצפה, $E_i = n p_i$ המספר הצפוי:\n\n$$\n\\chi^2 = \\sum_{i=1}^{k} \\frac{(O_i - E_i)^2}{E_i} \\;\\sim\\; \\chi^2_{k-1-m}\n$$\n\n$m$ הוא מספר הפרמטרים שאמדנו מהנתונים. **למה זה מבחן פרמטרי?** ההשערה היא על **הפרמטרים** $p_i$ של התפלגות מולטינומית, וההתפלגות $\\chi^2$ של הסטטיסטי היא רק **קירוב** למדגם גדול, שנשען על קירוב נורמלי לספירות. לכן צריך $E_i \\ge 5$ בכל קטגוריה. ב-KS, לעומת זאת, ההתפלגות של $D$ תחת $H_0$ מדויקת וזהה **לכל** $F_0$ רציפה.\n\n**דוגמה** (נתונים מדומים): מודל שפה ענה על 400 שאלות אמריקאיות, והתשובה הנכונה מפוזרת שווה בשווה בין A–D. האם המודל מעדיף אותיות מסוימות (הטיית מיקום, [position bias]{.en})?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanswers <- c(A = 124, B = 102, C = 95, D = 79)   # letters the model chose\nchisq.test(answers, p = rep(1/4, 4)) |> print(digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  answers\nX-squared = 10.46, df = 3, p-value = 0.015\n```\n\n\n:::\n:::\n\n\n$\\chi^2 = 10.46 > 7.81 = \\chi^2_{0.95,\\,3}$, ולכן **דוחים** $H_0$: יש הטיית מיקום.\n\n::: {.content-hidden when-format=\"revealjs\"}\n**החישוב הידני:** $E_i = 400 \\cdot \\tfrac14 = 100$ בכל קטגוריה.\n\n| | A | B | C | D |\n|---|---|---|---|---|\n| $O_i$ | 124 | 102 | 95 | 79 |\n| $\\frac{(O_i - E_i)^2}{E_i}$ | 5.76 | 0.04 | 0.25 | 4.41 |\n\n$\\chi^2 = 5.76 + 0.04 + 0.25 + 4.41 = 10.46$, עם $k - 1 = 3$ דרגות חופש: לא אמדנו אף פרמטר. כשמשתמשים במודל כ\"שופט\" בין תשובות, מערבבים את סדר התשובות. הסטייה הגדולה ביותר היא ב-A (נבחרת יותר מדי) וב-D (פחות מדי). ב-R רואים את זה ב-`chisq.test(...)$residuals`.\n\n**כשאומדים פרמטרים.** נניח שבודקים אם מספר הפניות לשעה מתפלג פואסונית, ואת $\\lambda$ אומדים מהנתונים עצמם ($\\hat\\lambda = \\bar{x}$). אז $m = 1$ ודרגות החופש הן $k - 2$. כל פרמטר שאומדים \"מקרב\" את ההתפלגות לנתונים, ולכן צריך להוריד דרגת חופש כדי לפצות.\n:::\n\n## מבחן [Kolmogorov–Smirnov]{.en} {.smaller}\n\n**כשהנתונים רציפים**, החלוקה לקטגוריות מאבדת מידע. מבחן KS משווה את פונקציית ההתפלגות **המצטברת**:\n\n- $F_n(x)$: פונקציית ההתפלגות האמפירית, החלק מהתצפיות שקטנות או שוות ל-$x$\n- $H_0: F(x) = F_0(x)$ לכל $x$, כש-$F_0$ רציפה ונתונה **במלואה**\n\n$$\nD = \\max_x \\left| F_n(x) - F_0(x) \\right|\n$$\n\n- דוחים את $H_0$ אם $D > D_{\\alpha,n}$ (טבלה). למדגם גדול: $D_{0.05,n} \\approx 1.36/\\sqrt{n}$\n- **בחישוב ידני:** ממיינים את התצפיות, ובודקים בכל $x_{(i)}$ את שני הצדדים של המדרגה:\n\n$$\nD = \\max_i \\left\\{ \\frac{i}{n} - F_0(x_{(i)}),\\;\\; F_0(x_{(i)}) - \\frac{i-1}{n} \\right\\}\n$$\n\n## דוגמה: זמנים בין פניות לצ׳אט {.smaller}\n\nמודל האיוש של מוקד שירות מניח שהזמן בין פניות לצ׳אט מתפלג **מעריכית עם ממוצע 2 דקות**. נמדדו 10 זמנים. האם הנתונים סותרים את ההנחה? $\\alpha = 0.05$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngaps <- c(0.4, 0.7, 1.1, 1.3, 1.9, 2.4, 3.6, 5.2, 6.8, 9.5)   # minutes\nn <- length(gaps)\ntibble(i = 1:n, x = gaps, F0 = pexp(gaps, rate = 1/2)) |>\n  mutate(`i/n - F0` = i/n - F0, `F0 - (i-1)/n` = F0 - (i - 1)/n) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|  i|   x|    F0| i/n - F0| F0 - (i-1)/n|\n|--:|---:|-----:|--------:|------------:|\n|  1| 0.4| 0.181|   -0.081|        0.181|\n|  2| 0.7| 0.295|   -0.095|        0.195|\n|  3| 1.1| 0.423|   -0.123|        0.223|\n|  4| 1.3| 0.478|   -0.078|        0.178|\n|  5| 1.9| 0.613|   -0.113|        0.213|\n|  6| 2.4| 0.699|   -0.099|        0.199|\n|  7| 3.6| 0.835|   -0.135|        0.235|\n|  8| 5.2| 0.926|   -0.126|        0.226|\n|  9| 6.8| 0.967|   -0.067|        0.167|\n| 10| 9.5| 0.991|    0.009|        0.091|\n\n\n:::\n:::\n\n\n## התוצאה\n\n$D_0 = 0.235$, בתצפית $x_{(7)} = 3.6$: $F_0(3.6) - \\frac{6}{10} = 0.835 - 0.6$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nks.test(gaps, \"pexp\", rate = 1/2) |> print(digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact one-sample Kolmogorov-Smirnov test\n\ndata:  gaps\nD = 0.2347, p-value = 0.563\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n- $D_0 = 0.235 < 0.409 = D_{0.05,10}$, ולכן **לא דוחים** את $H_0$\n- **אבל:** הממוצע במדגם הוא 3.29 דקות, לא 2. עם 10 תצפיות למבחן אין כמעט עוצמה. \"לא דחינו\" איננו \"הוכחנו\"\n\n::: {.content-hidden when-format=\"revealjs\"}\n**זהירות עם פרמטרים אמודים.** ה-p-value של KS נכון רק כש-$F_0$ נקבעה **לפני** שראינו את הנתונים. אם אומדים את הממוצע מהמדגם ואז בודקים מול מעריכית עם הממוצע הזה, ההתפלגות \"מותאמת\" לנתונים, $D$ יוצא קטן מדי, והמבחן כמעט לא ידחה. לבדיקת נורמליות עם פרמטרים אמודים יש מבחנים ייעודיים (למשל [Lilliefors]{.en} או [Shapiro–Wilk]{.en}).\n:::\n\n## KS לשני מדגמים\n\nאותו רעיון, בלי $F_0$: משווים בין שתי פונקציות התפלגות אמפיריות\n\n$$\nH_0: F_1(x) = F_2(x) \\qquad D = \\max_x \\left| F_{1,n}(x) - F_{2,m}(x) \\right|\n$$\n\n**דוגמה:** גרסה חדשה של שירות [inference]{.en} עלתה לאוויר. החציון של זמן התגובה כמעט לא השתנה, אבל משתמשים מתלוננים על \"קפיצות\". נדגמו 60 בקשות מכל גרסה. (נתונים מדומים)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\nlatency <- tibble(\n  version = rep(c(\"v1\", \"v2\"), each = 60),\n  ms = c(rlnorm(60, log(220), 0.25), rlnorm(60, log(220), 0.65))\n)\nlatency |> summarise(median = median(ms), iqr = IQR(ms), max = max(ms), .by = version)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  version median   iqr   max\n  <chr>    <dbl> <dbl> <dbl>\n1 v1        227.  63.5  361.\n2 v2        225. 180.  1048.\n```\n\n\n:::\n:::\n\n\n## שתי פונקציות התפלגות מצטברות\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\ngrid <- tibble(ms = sort(latency$ms)) |>\n  mutate(v1 = ecdf(latency$ms[latency$version == \"v1\"])(ms),\n         v2 = ecdf(latency$ms[latency$version == \"v2\"])(ms),\n         gap = abs(v1 - v2))\nmax_gap <- slice_max(grid, gap, n = 1, with_ties = FALSE)\n\nggplot(latency, aes(ms, colour = version)) +\n  stat_ecdf(linewidth = 0.9) +\n  geom_segment(aes(x = ms, xend = ms, y = v1, yend = v2), data = max_gap,\n               colour = \"grey20\", linewidth = 1, inherit.aes = FALSE) +\n  annotate(\"label\", x = max_gap$ms, y = (max_gap$v1 + max_gap$v2) / 2,\n           label = paste0(\"D = \", round(max_gap$gap, 2)), hjust = 1.1,\n           fill = \"white\", label.size = 0) +\n  scale_x_log10() +\n  scale_colour_manual(values = c(v1 = nanas_pal[[\"primary\"]], v2 = nanas_pal[[\"accent\"]])) +\n  labs(title = \"אותו חציון, פיזור שונה לגמרי\",\n       subtitle = \"הקו השחור: המרחק הגדול ביותר בין שתי הפונקציות\",\n       x = \"Response time (ms, log scale)\", y = \"F(x)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/ks-ecdf-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## KS מול סכום הדירוגים\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nv1 <- latency$ms[latency$version == \"v1\"]\nv2 <- latency$ms[latency$version == \"v2\"]\nc(rank_sum = wilcox.test(v1, v2)$p.value,\n  ks       = ks.test(v1, v2)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrank_sum       ks \n 0.95187  0.02763 \n```\n\n\n:::\n:::\n\n\n- **סכום הדירוגים** רגיש בעיקר להזזה של המיקום. החציונים כמעט שווים, ולכן הוא לא מוצא כלום\n- **KS** רגיש לכל הבדל בין ההתפלגויות: מיקום, פיזור או צורה. כאן הוא **דוחה** ב-$\\alpha = 0.05$\n- בשירות אמיתי, הזנב (האחוזון ה-95 או ה-99) הוא מה שהמשתמשים מרגישים. לכן כדאי לבדוק יותר מהחציון\n\n::: notes\nשאלה לכיתה: למה סכום הדירוגים \"עיוור\" כאן? כי ב-v2 יש גם ערכים קטנים מאוד וגם גדולים מאוד, והדרגות שלהם מתקזזות בסכום.\n:::\n\n# מתאם על דירוגים\n\n## למה לא פירסון?\n\nמתאם פירסון ($r$) מודד את חוזק הקשר **הלינארי** בין שני משתנים, אבל:\n\n- הוא רגיש מאוד לערכים חריגים\n- הוא לא מתאים למשתנים **אורדינליים** (סולמות סדר, כמו \"מרוצה מאוד\" עד \"לא מרוצה\")\n- הוא לא מתאים כשהשונות לא אחידה\n\n**החלופה:** מדדים שמבוססים על **הדרגות**, ולכן מודדים קשר **מונוטוני**, לא בהכרח לינארי.\n\n- **[Spearman's ρ]{.en}:** מתאם פירסון על הדרגות\n- **[Kendall's τ]{.en}:** מבוסס על זוגות בהתאמה מול זוגות בחוסר התאמה\n\n## [Kendall's τ]{.en}\n\nזוג תצפיות $(x_i, y_i), (x_j, y_j)$ הוא **בהתאמה** ([concordant]{.en}) אם $x_i > x_j$ וגם $y_i > y_j$, או $x_i < x_j$ וגם $y_i < y_j$. אחרת הזוג **בחוסר התאמה** ([discordant]{.en}).\n\n$$\n\\tau = \\frac{n_c - n_d}{n_0}, \\qquad n_0 = \\binom{n}{2}\n$$\n\n- $n_c$: מספר הזוגות בהתאמה, $n_d$: מספר הזוגות בחוסר התאמה\n- $-1 \\le \\tau \\le 1$\n- יש כמה גרסאות לטיפול בשוויון (ב-R: `tau-b`)\n\n## דוגמה: קשר מונוטוני וערך חריג אחד\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nset.seed(2026)   # own seed, so edits elsewhere in the lecture don't change this example\ncorr_data <- tibble(x = 1:30, y = exp(x / 6) + rnorm(30, sd = 1.5)) |>\n  add_row(x = 2, y = 160)   # one data-entry error\n\nstats <- c(\n  pearson  = cor(corr_data$x, corr_data$y),\n  spearman = cor(corr_data$x, corr_data$y, method = \"spearman\"),\n  kendall  = cor(corr_data$x, corr_data$y, method = \"kendall\")\n)\nround(stats, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pearson spearman  kendall \n    0.59     0.82     0.81 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(corr_data, aes(x, y)) +\n  geom_point(size = 2.5) +\n  annotate(\"label\", x = 3.5, y = 160, label = \"שגיאת הקלדה\", hjust = 0) +\n  labs(title = sprintf(\"Pearson = %.2f · Spearman = %.2f · Kendall = %.2f\",\n                       stats[\"pearson\"], stats[\"spearman\"], stats[\"kendall\"]),\n       subtitle = \"קשר מונוטוני ברור, עם תצפית חריגה אחת\",\n       x = \"x\", y = \"y\")\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/corr-sim-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nתצפית חריגה אחת (למשל שגיאת הקלדה) מספיקה כדי לגרור את פירסון כמעט לאפס. ספירמן וקנדל כמעט לא מושפעים ממנה. לקנדל יש גם פרשנות ישירה: $\\frac{1+\\tau}{2}$ הוא ההסתברות שזוג אקראי של תצפיות יהיה בהתאמה.\n:::\n\n# סיכום\n\n## מה לקחת מההרצאה {.smaller}\n\n| השאלה | פרמטרי | א-פרמטרי | ב-R |\n|---|---|---|---|\n| מרכז ההתפלגות | t / Z | סימן, דירוגים מסומנים | `binom.test`, `wilcox.test` |\n| מזווג | t מזווג | אותו מבחן על ההפרשים | `wilcox.test(paired = TRUE)` |\n| שני מדגמים ב״ת | t לשני מדגמים | סכום הדירוגים | `wilcox.test(x, y)` |\n| התאמה להתפלגות | | חי-בריבוע, KS | `chisq.test`, `ks.test` |\n| שתי התפלגויות | | KS לשני מדגמים | `ks.test(x, y)` |\n| מתאם | Pearson | Spearman, Kendall | `cor(method = )` |\n\n- שיטות א-פרמטריות לא \"חינמיות\": כשההנחות הפרמטריות **כן** מתקיימות, הן חלשות יותר\n- גם להן יש הנחות (רציפות, סימטריה, אותה צורת התפלגות). צריך לבדוק אותן\n\n# שאלת סיכום: ארגנטינה במונדיאל\n\n## הנתונים\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\narg <- read_csv(file.path(data_dir, \"argentina_world_cup.csv\"), show_col_types = FALSE)\n\nggplot(arg, aes(year, rank, colour = host_in_europe)) +\n  geom_point(size = 3.5) +\n  geom_point(data = filter(arg, is.na(rank)), aes(y = 18), shape = 4, size = 3, colour = \"grey50\") +\n  scale_y_reverse(breaks = c(1, 4, 8, 12, 16)) +\n  scale_colour_manual(values = c(`TRUE` = nanas_pal[[\"primary\"]], `FALSE` = nanas_pal[[\"accent\"]]),\n                      labels = c(`TRUE` = \"באירופה\", `FALSE` = \"מחוץ לאירופה\")) +\n  labs(title = \"הדירוג של ארגנטינה במונדיאלים, 1930–2022\",\n       subtitle = \"×: לא השתתפה או לא הגיעה ל-16 הגדולות\",\n       x = \"Year\", y = \"Final rank\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](01-nonparametric_files/figure-html/argentina-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## השאלות {.smaller}\n\nא. תנו לפחות שתי סיבות לכך שאי אפשר להניח שהדירוג של ארגנטינה מתפלג נורמלית.\n\nב. על סמך המונדיאלים **עד 2018**: האם אפשר לקבוע ב-$\\alpha = 0.05$ שבמחצית מהמונדיאלים העתידיים ארגנטינה תעבור את רבע הגמר (כלומר תגיע לדירוג 1–4)?\n\nג. מה ההסתברות לטעות מסוג ראשון במבחן שביצעתם בסעיף ב׳?\n\nד. האם ארגנטינה מצליחה יותר במונדיאלים שנערכים **מחוץ** לאירופה? ($\\alpha = 0.05$)\n\nה. **עדכון:** הוסיפו את מונדיאל 2022 (קטאר, ארגנטינה זכתה). האם המסקנה בסעיף ב׳ משתנה? מה זה מלמד אתכם?\n\nו. **ביקורת:** איך טיפלנו בשנים המסומנות ב-×? האם זה הוגן?\n\n## פתרון (סעיפים א–ג)\n\n::: {.content-hidden when-format=\"revealjs\"}\n**א.** הדירוג בדיד ולא רציף. התומך שלו חסום (1 עד 16 ומעלה), בניגוד לנורמלית שהתומך שלה כל הישר. וההתפלגות לא סימטרית.\n\n**ב.** $H_0: \\tilde\\mu = 4.5$ (החציון מפריד בין דירוג 4 לשאר). אי אפשר להניח סימטריה, ולכן משתמשים במבחן הסימן.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\narg18 <- arg |> filter(year <= 2018) |> mutate(rank_filled = coalesce(rank, 17))\nn_top4 <- sum(arg18$rank_filled < 4.5)\nc(n = nrow(arg18), r0 = n_top4, R_crit = sign_critical(nrow(arg18), 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n     r0 R_crit \n    21      5      5 \n```\n\n\n:::\n\n```{.r .cell-code}\nbinom.test(n_top4, nrow(arg18))$p.value     # = alpha in (c): 2 * P(r <= 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0266\n```\n\n\n:::\n:::\n\n\n$r_0 = 5 \\le 5 = R^*_{0.05,21}$, ולכן **דוחים** $H_0$: אי אפשר לקבוע שהחציון הוא 4.5. התשובה לשאלה היא **לא**.\n\n**ג.** $\\alpha = 2\\left(\\tfrac{1}{2}\\right)^{21}\\sum_{i=0}^{5}\\binom{21}{i} = 0.027$\n\n## פתרון (סעיפים ד–ו) {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwith(arg18, wilcox.test(rank_filled[!host_in_europe], rank_filled[host_in_europe],\n                        exact = FALSE))$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4773\n```\n\n\n:::\n\n```{.r .cell-code}\narg22 <- arg |> mutate(rank_filled = coalesce(rank, 17))\nbinom.test(sum(arg22$rank_filled < 4.5), nrow(arg22))$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05248\n```\n\n\n:::\n:::\n\n\n- **ד.** $p \\approx 0.48$: **לא דוחים**. אין ראיה לכך שארגנטינה מצליחה יותר מחוץ לאירופה\n- **ה.** עם 2022: $r_0 = 6 > 5 = R^*_{0.05,22}$ ו-$p = 0.052$, ולכן **כבר לא דוחים**. טורניר אחד הפך את המסקנה. במדגם קטן, תוצאה שנמצאת על סף המובהקות היא שבירה\n- **ו.** 1938, 1950 ו-1954 הן שנים שבהן ארגנטינה **לא השתתפה בכלל**. אם מתייחסים אליהן כאל \"דירוג גרוע\", מערבבים שתי שאלות שונות. איך המסקנות משתנות אם משמיטים אותן?\n",
    "supporting": [
      "01-nonparametric_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}