{
  "hash": "e699b5e4474a4ea86495d74bd7d3b8ff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3. רגרסיה לינארית מרובה\"\nsubtitle: \"ניתוח נתונים סטטיסטי · הרצאה 3\"\nauthor: \"ד״ר עדי שריד\"\ndate: last-modified\nformat:\n  revealjs:\n    output-file: 03-multiple-regression-slides.html\n---\n\n\n\n## על מה נדבר היום\n\n- **תזכורת:** רגרסיה לינארית פשוטה, שיטת הריבועים הפחותים, ואיך קוראים את הפלט\n- **רגרסיה מרובה:** כמה משתנים מסבירים, רישום מטריציוני, ופרשנות של \"כל השאר קבוע\"\n- **מבחני השערות:** מבחן t לכל מקדם, מבחן F לכל המודל, ומבחן F חלקי\n- **$R^2$ ו-$R^2$ מתוקן**\n- **משתנים קטגוריים ואינטראקציות**\n- **בדיקת ההנחות:** שאריות ומולטיקולינאריות\n- **בחירת משתנים, רווחי סמך ורווחי חיזוי**\n\n# תזכורת: רגרסיה לינארית פשוטה ([Simple linear regression]{.en})\n\n## השאלה: כמה מעבד צורכת כל אלף בקשות?\n\nצוות התשתיות מתכנן קיבולת ([capacity planning]{.en}) לשירות חדש. בעשרה חלונות זמן נמדדו העומס (אלפי בקשות בדקה) וניצולת המעבד (CPU, באחוזים).\n\n**השאלות:** בכמה עולה ניצולת המעבד עם כל אלף בקשות נוספות בדקה? והאם הקשר הזה \"אמיתי\", או שהוא יכול להיות מקרי?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncpu <- tibble(\n  load = c(10, 11.5, 14.5, 12, 15, 16.6, 12.5, 13, 14, 17),       # k requests / min\n  util = c(15, 16.6, 20.2, 16.3, 19.4, 24.4, 17, 17.1, 17.7, 24.4)  # CPU %\n)\n```\n:::\n\n\n## הנתונים\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(cpu, aes(load, util)) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = nanas_pal[[\"grey\"]], linewidth = 0.8) +\n  geom_point(size = 3) +\n  labs(title = \"ככל שהעומס עולה, המעבד עובד קשה יותר\",\n       subtitle = \"עשרה חלונות זמן · הקו: קו הריבועים הפחותים\",\n       x = \"Load (k requests / min)\", y = \"CPU utilisation (%)\")\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/cpu-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## המודל {.smaller}\n\n$$\nY_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i \\qquad i = 1, \\dots, n\n$$\n\n- $\\beta_0$ הוא **החותך** ([intercept]{.en}) ו-$\\beta_1$ הוא **השיפוע** ([slope]{.en}): בכמה משתנה התוחלת של $Y$ כש-$x$ עולה ביחידה אחת\n- $E(Y \\mid x) = \\beta_0 + \\beta_1 x$ ו-$V(Y \\mid x) = \\sigma^2$\n\n**ההנחות על השגיאות** $\\varepsilon_i$:\n\n1. **לינאריות:** התוחלת של $Y$ היא פונקציה לינארית של $x$\n2. **אי-תלות:** השגיאות בלתי תלויות זו בזו\n3. **שונות קבועה** ([homoscedasticity]{.en}): אותה $\\sigma^2$ לכל ערך של $x$\n4. **נורמליות:** $\\varepsilon_i \\sim N(0, \\sigma^2)$. נדרשת למבחנים ולרווחי הסמך, לא לאמידה עצמה\n\n## שיטת הריבועים הפחותים ([Least squares]{.en}) {.smaller}\n\nמחפשים את הקו שממזער את סכום ריבועי הסטיות האנכיות:\n\n$$\nL(\\beta_0, \\beta_1) = \\sum_{i=1}^{n} \\left(y_i - \\beta_0 - \\beta_1 x_i\\right)^2\n$$\n\nגוזרים לפי $\\beta_0$ ולפי $\\beta_1$ ומשווים לאפס (**משוואות נורמליות**), ומקבלים:\n\n$$\n\\hat\\beta_1 = \\frac{S_{xy}}{S_{xx}} \\qquad \\hat\\beta_0 = \\bar y - \\hat\\beta_1 \\bar x\n$$\n\n$$\nS_{xx} = \\sum_{i=1}^{n} (x_i - \\bar x)^2 = \\sum x_i^2 - n\\bar x^2 \\qquad\nS_{xy} = \\sum_{i=1}^{n} (x_i - \\bar x)(y_i - \\bar y) = \\sum x_i y_i - n \\bar x \\bar y\n$$\n\n::: {.content-hidden when-format=\"revealjs\"}\n**למה דווקא ריבועים?** יש קריטריונים אחרים. אפשר למזער את הסטייה **המרבית** ([minimax]{.en}), או את סכום הסטיות **בערך מוחלט** ([least absolute deviations]{.en}, שעמיד יותר לערכים חריגים). לריבועים הפחותים יש שלושה יתרונות. יש להם פתרון סגור. לפי משפט [Gauss–Markov]{.en} הם האומד הלינארי חסר ההטיה בעל השונות הקטנה ביותר, גם בלי הנחת נורמליות. וכשהשגיאות נורמליות, הם גם אומד הנראות המרבית.\n:::\n\n## חישוב ידני {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncpu |> summarise(n = n(), x_bar = mean(load), y_bar = mean(util),\n                 Sxx = sum((load - x_bar)^2),\n                 Sxy = sum((load - x_bar) * (util - y_bar)),\n                 Syy = sum((util - y_bar)^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n      n x_bar y_bar   Sxx   Sxy   Syy\n  <int> <dbl> <dbl> <dbl> <dbl> <dbl>\n1    10  13.6  18.8  45.0  62.8  97.9\n```\n\n\n:::\n:::\n\n\n$$\n\\hat\\beta_1 = \\frac{62.80}{44.99} = 1.396 \\qquad\n\\hat\\beta_0 = 18.81 - 1.396 \\cdot 13.61 = -0.188\n$$\n\n$$\nSS_R = \\hat\\beta_1 S_{xy} = 87.66 \\qquad SS_E = S_{yy} - SS_R = 97.91 - 87.66 = 10.25 \\qquad\n\\hat\\sigma^2 = \\frac{SS_E}{n-2} = 1.281\n$$\n\n$$\nse(\\hat\\beta_1) = \\sqrt{\\frac{\\hat\\sigma^2}{S_{xx}}} = \\sqrt{\\frac{1.281}{44.99}} = 0.169 \\qquad\nt = \\frac{1.396}{0.169} = 8.27 \\qquad R^2 = \\frac{SS_R}{S_{yy}} = 0.895\n$$\n\n## אותו חישוב ב-R {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_cpu <- lm(util ~ load, data = cpu)\nsummary(fit_cpu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = util ~ load, data = cpu)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.6544 -0.7095 -0.0565  0.8273  1.4163 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -0.188      2.324   -0.08     0.94    \nload           1.396      0.169    8.27  3.4e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.13 on 8 degrees of freedom\nMultiple R-squared:  0.895,\tAdjusted R-squared:  0.882 \nF-statistic: 68.4 on 1 and 8 DF,  p-value: 3.43e-05\n```\n\n\n:::\n:::\n\n\n## איך קוראים את הפלט {.smaller}\n\n- **`Estimate`**: המקדמים. כל אלף בקשות נוספות בדקה מעלות את ניצולת המעבד ב-1.4 נקודות אחוז בממוצע\n- **`Std. Error`**: שגיאת התקן של כל מקדם, $se(\\hat\\beta_j)$\n- **`t value`** ו-**`Pr(>|t|)`**: מבחן $H_0: \\beta_j = 0$, עם $t = \\hat\\beta_j / se(\\hat\\beta_j)$ ו-$n - 2 = 8$ דרגות חופש. לשיפוע $p = 0.00003$, ולכן **דוחים**: הקשר לא מקרי\n- **`Residual standard error`**: $\\hat\\sigma = \\sqrt{MS_E} = 1.13$. זו הסטייה הטיפוסית של תצפית מהקו, ביחידות של $Y$\n- **`Multiple R-squared`**: 89.5% מהשונות בניצולת המעבד מוסברים על ידי העומס\n- **`F-statistic`**: מבחן לכל המודל. ברגרסיה פשוטה $F = t^2$: $8.27^2 = 68.4$\n\n::: notes\nלשאול את הכיתה: למה החותך לא מובהק, ולמה שגיאת התקן שלו כל כך גדולה (2.3)? זה מוביל לשקף הבא.\n:::\n\n## מה עושים עם החותך? מירכוז ([Centering]{.en}) {.smaller}\n\nהחותך הוא הניצולת הצפויה כש-$x = 0$, הרחק מטווח הנתונים (10 עד 17). לכן השונות שלו גדולה:\n\n$$\nV(\\hat\\beta_0) = \\sigma^2 \\left[\\frac{1}{n} + \\frac{\\bar x^2}{S_{xx}}\\right]\n$$\n\nאם מחסירים מ-$x$ את הממוצע שלו, $\\bar x = 0$, והחותך הופך ל-$\\bar y$: הניצולת הצפויה **בעומס הממוצע**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(util ~ I(load - mean(load)), data = cpu) |> summary() |> coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Estimate Std. Error t value  Pr(>|t|)\n(Intercept)            18.810     0.3579  52.551 1.906e-11\nI(load - mean(load))    1.396     0.1688   8.272 3.431e-05\n```\n\n\n:::\n:::\n\n\n- השיפוע לא השתנה, ושגיאת התקן של החותך ירדה מ-2.32 ל-$\\hat\\sigma / \\sqrt{n} = 1.132 / \\sqrt{10} = 0.358$\n- הקו הוא אותו קו. השתנתה רק השאלה שהחותך עונה עליה\n\n## פירוק השונות וטבלת ANOVA {.smaller}\n\n$$\n\\underbrace{\\sum_{i}(y_i - \\bar y)^2}_{SS_T} = \\underbrace{\\sum_{i}(\\hat y_i - \\bar y)^2}_{SS_R} + \\underbrace{\\sum_{i}(y_i - \\hat y_i)^2}_{SS_E}\n$$\n\n| מקור | סכום ריבועים | דרגות חופש | ממוצע ריבועים | $F$ |\n|---|---|---|---|---|\n| רגרסיה | $SS_R$ | $1$ | $MS_R = SS_R / 1$ | $MS_R / MS_E$ |\n| שגיאה | $SS_E$ | $n - 2$ | $MS_E = SS_E / (n-2)$ | |\n| סך הכול | $SS_T$ | $n - 1$ | | |\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(fit_cpu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: util\n          Df Sum Sq Mean Sq F value  Pr(>F)    \nload       1   87.7    87.7    68.4 3.4e-05 ***\nResiduals  8   10.2     1.3                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**מקדם המתאם המרובה:** $R^2 = SS_R / SS_T = 87.66 / 97.91 = 0.895$\n\nשני הרכיבים אי-שליליים, ולכן תמיד $0 \\le R^2 \\le 1$.\n\n# רגרסיה לינארית מרובה ([Multiple linear regression]{.en})\n\n## השאלה: מה קובע את זמן התגובה של מודל שפה?\n\nחברה משתמשת ב-API של מודל שפה, בשלושה גדלים: `small`, `medium` ו-`large`. המשתמשים מתלוננים על המתנה ארוכה.\n\n**השאלות:**\n\n- כמה זמן מוסיף כל טוקן ([token]{.en}) בתשובה? וכל אלף טוקנים בקלט?\n- האם מודל השפה הגדול **עצמו** איטי יותר, או שהוא פשוט כותב תשובות ארוכות יותר?\n- כמה זמן תיקח קריאה עם 2,000 טוקנים בקלט ו-500 בפלט למודל השפה הגדול?\n\n**הנתונים:** 250 קריאות מהלוגים (נתונים מדומים). לכל קריאה: גודל מודל השפה, מספר הטוקנים בקלט ובפלט, מספר המסמכים שצורפו לפרומפט ([RAG]{.en}), השעה ביום, וזמן התגובה בשניות.\n\n## הנתונים\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(303)   # own seed, so edits elsewhere in the lecture don't change this example\nn_calls <- 250\nsizes <- c(\"small\", \"medium\", \"large\")\nmedian_output <- c(small = 250,   medium = 350,   large = 500)    # tokens\nsec_per_token <- c(small = 0.010, medium = 0.018, large = 0.030)\n\nllm <- tibble(\n  model    = factor(sample(sizes, n_calls, replace = TRUE, prob = c(0.5, 0.3, 0.2)), sizes),\n  rag_docs = rpois(n_calls, 3),                         # documents added to the prompt\n  input_tokens  = round(300 + 550 * rag_docs + rlnorm(n_calls, log(400), 0.6)),\n  output_tokens = round(rlnorm(n_calls, log(median_output[as.character(model)]), 0.5)),\n  hour     = sample(0:23, n_calls, replace = TRUE)\n) |>\n  mutate(latency = 0.8 + 0.25 * input_tokens / 1000 +\n           sec_per_token[as.character(model)] * output_tokens + rnorm(n_calls, 0, 1),\n         latency = round(latency, 2),\n         input_k = input_tokens / 1000)\n\nllm |> select(model, input_tokens, output_tokens, rag_docs, hour, latency) |> head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  model  input_tokens output_tokens rag_docs  hour latency\n  <fct>         <dbl>         <dbl>    <int> <int>   <dbl>\n1 small          3585           155        5    21    1.71\n2 large          1851           478        0     1   15.7 \n3 medium         3140           161        5    16    3.89\n4 medium         2382           200        3     6    4.83\n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\n**איך נבנו הנתונים.** זמן התגובה מורכב מקבוע של 0.8 שניות (רשת ותור), מ-0.25 שניות לכל אלף טוקנים בקלט (קריאת הפרומפט, [prefill]{.en}), ומזמן לכל טוקן בפלט שתלוי בגודל מודל השפה: 10, 18 ו-30 מילישניות. למודל השפה הגדול יש גם תשובות ארוכות יותר. מספר המסמכים משפיע על זמן התגובה **רק** דרך מספר הטוקנים בקלט, והשעה ביום לא משפיעה בכלל. כשקוראים את התוצאות, כדאי לבדוק כמה מהם הרגרסיה מצליחה לשחזר.\n:::\n\n## זמן התגובה מול אורך התשובה\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nggplot(llm, aes(output_tokens, latency, colour = model)) +\n  geom_point(alpha = 0.7) +\n  scale_colour_manual(values = model_cols) +\n  labs(title = \"תשובה ארוכה יותר, המתנה ארוכה יותר\",\n       subtitle = \"וכל מודל שפה עם שיפוע משלו\",\n       x = \"Output tokens\", y = \"Latency (s)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/llm-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## המודל {.smaller}\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_k x_{ik} + \\varepsilon_i \\qquad \\varepsilon_i \\sim N(0, \\sigma^2)\n$$\n\n- אותן הנחות כמו ברגרסיה פשוטה, עם $k$ משתנים מסבירים ([predictors]{.en})\n- **הפרשנות של $\\beta_j$:** השינוי בתוחלת של $Y$ כש-$x_j$ עולה ביחידה אחת, **וכל שאר המשתנים במודל נשארים קבועים**\n- \"לינארי\" פירושו לינארי **בפרמטרים** $\\beta$. אפשר להכניס $x^2$, $\\log x$ או מכפלה $x_1 x_2$, והמודל עדיין לינארי\n\nנתחיל משני משתנים מסבירים: הטוקנים בקלט (באלפים) והטוקנים בפלט.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit2 <- lm(latency ~ input_k + output_tokens, data = llm)\ncoef(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)       input_k output_tokens \n     -1.75379       0.07958       0.02634 \n```\n\n\n:::\n:::\n\n\n## רישום מטריציוני ([Matrix form]{.en}) {.smaller}\n\n$$\n\\mathbf{y} = X\\boldsymbol\\beta + \\boldsymbol\\varepsilon \\qquad\nX = \\begin{pmatrix} 1 & x_{11} & \\cdots & x_{1k} \\\\ \\vdots & \\vdots & & \\vdots \\\\ 1 & x_{n1} & \\cdots & x_{nk} \\end{pmatrix}_{n \\times (k+1)}\n$$\n\nממזערים את $L(\\boldsymbol\\beta) = (\\mathbf{y} - X\\boldsymbol\\beta)'(\\mathbf{y} - X\\boldsymbol\\beta)$. הנגזרת היא $-2X'\\mathbf{y} + 2X'X\\boldsymbol\\beta$, ומשווים אותה לאפס:\n\n$$\nX'X\\hat{\\boldsymbol\\beta} = X'\\mathbf{y} \\quad\\Longrightarrow\\quad \\hat{\\boldsymbol\\beta} = (X'X)^{-1}X'\\mathbf{y}\n$$\n\n- העמודה של אחדות ב-$X$ היא החותך\n- צריך ש-$X'X$ תהיה הפיכה: אף משתנה לא יכול להיות צירוף לינארי מדויק של האחרים\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nX <- model.matrix(~ input_k + output_tokens, data = llm)   # adds the column of ones\ny <- llm$latency\nsolve(t(X) %*% X) %*% t(X) %*% y                            # same as coef(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  [,1]\n(Intercept)   -1.75379\ninput_k        0.07958\noutput_tokens  0.02634\n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\n**הקשר לרגרסיה פשוטה.** כש-$k = 1$, המטריצה $X'X$ היא $\\begin{pmatrix} n & \\sum x_i \\\\ \\sum x_i & \\sum x_i^2 \\end{pmatrix}$, ו-$X'\\mathbf{y} = \\begin{pmatrix} \\sum y_i \\\\ \\sum x_i y_i \\end{pmatrix}$. אלה בדיוק שתי המשוואות הנורמליות מקודם, ופתרונן נותן את $\\hat\\beta_1 = S_{xy}/S_{xx}$.\n:::\n\n## תכונות האומדים {.smaller}\n\n- **חסרי הטיה:** $E(\\hat{\\boldsymbol\\beta}) = \\boldsymbol\\beta$\n- **מטריצת השונויות:** $V(\\hat{\\boldsymbol\\beta}) = \\sigma^2 (X'X)^{-1}$. נסמן $C = (X'X)^{-1}$\n- **אומד ל-$\\sigma^2$:** $\\hat\\sigma^2 = MS_E = \\dfrac{SS_E}{n - k - 1}$. מאבדים דרגת חופש על כל מקדם, כולל החותך\n\n$$\nse(\\hat\\beta_j) = \\sqrt{\\hat\\sigma^2 C_{jj}} \\qquad\nt = \\frac{\\hat\\beta_j}{se(\\hat\\beta_j)} \\sim t_{n-k-1} \\qquad\n\\hat\\beta_j \\pm t_{1-\\alpha/2,\\, n-k-1} \\cdot se(\\hat\\beta_j)\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma2_hat <- sum(resid(fit2)^2) / (nrow(X) - ncol(X))     # SSE / (n - k - 1)\nsqrt(diag(sigma2_hat * solve(t(X) %*% X)))                  # = \"Std. Error\" in summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)       input_k output_tokens \n    0.7254406     0.2442116     0.0009362 \n```\n\n\n:::\n:::\n\n\n## הפלט המלא {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = latency ~ input_k + output_tokens, data = llm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-12.084  -1.880  -0.418   1.786   9.959 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -1.753788   0.725441   -2.42    0.016 *  \ninput_k        0.079583   0.244212    0.33    0.745    \noutput_tokens  0.026340   0.000936   28.13   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.56 on 247 degrees of freedom\nMultiple R-squared:  0.762,\tAdjusted R-squared:  0.76 \nF-statistic:  396 on 2 and 247 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\n## איך קוראים את הפלט {.smaller}\n\n- **`output_tokens = 0.0263`**: כל טוקן נוסף בתשובה מוסיף כ-26 מילישניות, **כשמספר הטוקנים בקלט קבוע**. $t = 28$, מובהק מאוד\n- **`input_k`**: לא מובהק ($p = 0.75$). האם הקלט באמת לא משפיע? נחזור לזה\n- **`F-statistic: 396 on 2 and 247 DF`**: מבחן לכל המודל. $k = 2$ ו-$n - k - 1 = 247$\n- **`R-squared = 0.762`**: שני המשתנים יחד מסבירים 76% מהשונות בזמן התגובה\n- **`Residual standard error = 3.56`**: קריאה טיפוסית רחוקה 3.6 שניות מהחיזוי. זה הרבה, כשהחציון הוא 6 שניות\n\n::: notes\ninput_k יוצא לא מובהק כי המודל עדיין שגוי: הוא מתעלם מגודל מודל השפה, וכל הרעש הזה נכנס לשגיאה ומסתיר את האפקט. אל תגלו להם עדיין, זה יתגלה בהמשך.\n:::\n\n# מבחני השערות במודל המרובה\n\n## מבחן F לכל המודל {.smaller}\n\n$$\nH_0: \\beta_1 = \\beta_2 = \\dots = \\beta_k = 0 \\qquad H_1: \\text{לפחות מקדם אחד שונה מאפס}\n$$\n\n| מקור | סכום ריבועים | דרגות חופש | ממוצע ריבועים | $F$ |\n|---|---|---|---|---|\n| רגרסיה | $SS_R$ | $k$ | $MS_R = SS_R / k$ | $MS_R / MS_E$ |\n| שגיאה | $SS_E$ | $n - k - 1$ | $MS_E = SS_E / (n-k-1)$ | |\n| סך הכול | $SS_T$ | $n - 1$ | | |\n\nדוחים את $H_0$ אם $F > F_{1-\\alpha;\\, k,\\, n-k-1}$.\n\n- דחייה אומרת רק שלפחות משתנה **אחד** עוזר. היא לא אומרת איזה\n- מבחני ה-t בודקים כל מקדם **בנוכחות כל השאר**. משתנה יכול להיות לא מובהק לבד, ובכל זאת חשוב\n\n## $R^2$ ו-$R^2$ מתוקן ([Adjusted R²]{.en}) {.smaller}\n\n$$\nR^2 = \\frac{SS_R}{SS_T} = 1 - \\frac{SS_E}{SS_T} \\qquad\nR^2_{adj} = 1 - \\frac{SS_E / (n - k - 1)}{SS_T / (n - 1)} = 1 - (1 - R^2)\\frac{n - 1}{n - k - 1}\n$$\n\n- **הבעיה של $R^2$:** הוא **אף פעם לא יורד** כשמוסיפים משתנה, גם אם המשתנה הוא רעש טהור\n- **$R^2$ המתוקן** \"מעניש\" על כל משתנה נוסף. הוא עולה רק אם המשתנה מקטין את $MS_E$. למקסם אותו זה כמו למזער את $MS_E$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(8)\nllm_noise <- llm |> mutate(noise1 = rnorm(n()), noise2 = rnorm(n()), noise3 = rnorm(n()))\nfit_noise <- lm(latency ~ input_k + output_tokens + noise1 + noise2 + noise3, data = llm_noise)\nrbind(fit2      = c(R2 = summary(fit2)$r.squared,      adj = summary(fit2)$adj.r.squared),\n      fit_noise = c(R2 = summary(fit_noise)$r.squared, adj = summary(fit_noise)$adj.r.squared))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              R2    adj\nfit2      0.7622 0.7603\nfit_noise 0.7628 0.7580\n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nשלושה משתני רעש העלו את $R^2$, ו-$R^2_{adj}$ ירד. אבל גם $R^2_{adj}$ לא חסין: הוא עולה בכל פעם שמוסיפים משתנה שערך ה-$|t|$ שלו גדול מ-1. למשתנה רעש זה קורה בערך בשליש מהמקרים. לכן $R^2_{adj}$ מתאים להשוואה גסה בין מודלים, ולא כהוכחה שמשתנה שייך למודל.\n:::\n\n## תרגיל: השלימו את הפלט {.smaller}\n\nפלט של רגרסיה עם $n = 30$ תצפיות ו-$k = 3$ משתנים מסבירים. חלק מהערכים נמחקו:\n\n| מקור | סכום ריבועים | דרגות חופש | ממוצע ריבועים | $F$ |\n|---|---|---|---|---|\n| רגרסיה | 600 | (א) | (ב) | (ג) |\n| שגיאה | (ד) | (ה) | (ו) | |\n| סך הכול | 860 | 29 | | |\n\nהשלימו את הטבלה, וחשבו את $R^2$, את $R^2_{adj}$ ואת $\\hat\\sigma$. האם המודל מובהק ב-$\\alpha = 0.05$? ($F_{0.95;\\,3,\\,26} = 2.98$)\n\n::: {.content-hidden when-format=\"revealjs\"}\n**פתרון.** (א) $k = 3$. (ב) $MS_R = 600/3 = 200$. (ד) $SS_E = 860 - 600 = 260$. (ה) $n - k - 1 = 26$. (ו) $MS_E = 260/26 = 10$. (ג) $F = 200/10 = 20 > 2.98$, ולכן המודל מובהק. $R^2 = 600/860 = 0.698$, $R^2_{adj} = 1 - \\frac{10}{860/29} = 1 - \\frac{10}{29.66} = 0.663$, ו-$\\hat\\sigma = \\sqrt{10} = 3.16$.\n:::\n\n# משתנים קטגוריים ([Categorical variables]{.en})\n\n## משתני דמה ([Dummy variables]{.en}) {.smaller}\n\nלמשתנה קטגורי עם $m$ רמות מוסיפים $m - 1$ **משתני דמה** (אינדיקטורים). רמה אחת היא **רמת הבסיס** ([reference level]{.en}), ולה אין משתנה משלה.\n\n$$\nD_{medium} = \\begin{cases} 1 & \\text{medium} \\\\ 0 & \\text{אחרת} \\end{cases} \\qquad\nD_{large} = \\begin{cases} 1 & \\text{large} \\\\ 0 & \\text{אחרת} \\end{cases}\n$$\n\n$$\nY = \\beta_0 + \\beta_1 x_{input} + \\beta_2 x_{output} + \\beta_3 D_{medium} + \\beta_4 D_{large} + \\varepsilon\n$$\n\n- $\\beta_4$: בכמה קריאה למודל השפה הגדול איטית יותר מקריאה למודל השפה הקטן, **באותו מספר טוקנים**\n- למה לא $m$ משתנים? כי אז $D_{small} + D_{medium} + D_{large} = 1$, בדיוק כמו עמודת החותך, ו-$X'X$ לא הפיכה\n- R יוצר את משתני הדמה בעצמו מכל `factor`. רמת הבסיס היא הרמה הראשונה (`levels`)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel.matrix(~ model, data = llm) |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) modelmedium modellarge\n1           1           0          0\n2           1           0          1\n3           1           1          0\n```\n\n\n:::\n:::\n\n\n## האם מודל השפה הגדול איטי יותר? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_raw <- lm(latency ~ model, data = llm)                            # model only\nfit3    <- lm(latency ~ input_k + output_tokens + model, data = llm)  # same length of answer\nrbind(raw = coef(fit_raw)[c(\"modelmedium\", \"modellarge\")],\n      adjusted = coef(fit3)[c(\"modelmedium\", \"modellarge\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         modelmedium modellarge\nraw            4.930     15.182\nadjusted       2.047      9.018\n```\n\n\n:::\n:::\n\n\n- **בלי לשלוט באורך התשובה:** קריאה למודל השפה הגדול איטית ב-15.2 שניות מקריאה למודל השפה הקטן\n- **באותו מספר טוקנים:** הפער יורד ל-9 שניות\n- חלק מהפער נובע מכך שמודל השפה הגדול כותב תשובות ארוכות יותר. זה **משתנה מערבב** ([confounder]{.en})\n- \"שליטה\" במשתנה ([controlling for]{.en}) פירושה להשוות קריאות עם אותו ערך שלו\n\n## מבחן F חלקי ([Partial F test]{.en}) {.smaller}\n\n**השאלה:** האם גודל מודל השפה משפיע בכלל? זו השערה על **שני** מקדמים יחד, $H_0: \\beta_3 = \\beta_4 = 0$. אי אפשר לענות עליה עם שני מבחני t נפרדים.\n\nמשווים בין **המודל המלא** ([full]{.en}) לבין **המודל המצומצם** ([reduced]{.en}), שבו $H_0$ נכונה:\n\n$$\nF = \\frac{(SS_E^{R} - SS_E^{F}) / q}{SS_E^{F} / (n - k - 1)} \\sim F_{q,\\; n-k-1}\n$$\n\n$q$ הוא מספר המקדמים שנבדקים, ו-$k$ הוא מספר המשתנים במודל **המלא**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(fit2, fit3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: latency ~ input_k + output_tokens\nModel 2: latency ~ input_k + output_tokens + model\n  Res.Df  RSS Df Sum of Sq   F Pr(>F)    \n1    247 3125                            \n2    245  911  2      2213 297 <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## איך קוראים את הפלט\n\n- **`RSS`**: סכום ריבועי השגיאות ($SS_E$) של כל מודל. משתני הדמה הורידו אותו מ-3125 ל-911\n- **`Df = 2`**: הוספנו $q = 2$ מקדמים\n- **בחישוב ידני** (דוחים את $H_0$: גודל מודל השפה משפיע):\n\n$$\nF = \\frac{(3125 - 911) / 2}{911 / 245} = 297\n$$\n\n- כש-$q = 1$, מבחן F החלקי שקול למבחן t של אותו מקדם: $F = t^2$\n- מבחן F לכל המודל הוא מקרה פרטי: המודל המצומצם הוא מודל עם חותך בלבד\n\n# אינטראקציות ([Interactions]{.en})\n\n## האם הקווים מקבילים?\n\nברגרסיה `fit3` לכל מודל שפה יש חותך משלו, אבל **אותו שיפוע**: אותו זמן לכל טוקן בתשובה. זה סביר?\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nggplot(augment(fit3), aes(output_tokens, colour = model)) +\n  geom_point(aes(y = latency), alpha = 0.5) +\n  geom_smooth(aes(y = .fitted), method = \"lm\", se = FALSE, linewidth = 1) +\n  scale_colour_manual(values = model_cols) +\n  labs(title = \"קווים מקבילים לא מתאימים לנתונים\",\n       subtitle = \"הקווים: החיזוי של רגרסיה בלי אינטראקציה (בממוצע הקלט)\",\n       x = \"Output tokens\", y = \"Latency (s)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/parallel-lines-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## מודל עם אינטראקציה {.smaller}\n\n**אינטראקציה** פירושה שההשפעה של משתנה אחד תלויה בערך של משתנה אחר. כאן: הזמן לכל טוקן תלוי בגודל מודל השפה.\n\n$$\nY = \\beta_0 + \\beta_1 x_{in} + \\beta_2 x_{out} + \\beta_3 D_{med} + \\beta_4 D_{lrg} + \\beta_5\\, x_{out} D_{med} + \\beta_6\\, x_{out} D_{lrg} + \\varepsilon\n$$\n\n| מודל שפה | השיפוע של $x_{out}$ |\n|---|---|\n| small | $\\beta_2$ |\n| medium | $\\beta_2 + \\beta_5$ |\n| large | $\\beta_2 + \\beta_6$ |\n\nב-R, `output_tokens * model` הוא קיצור של `output_tokens + model + output_tokens:model`.\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nfit4 <- lm(latency ~ input_k + output_tokens * model, data = llm)\nsummary(fit4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = latency ~ input_k + output_tokens * model, data = llm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.3999 -0.7069  0.0906  0.6431  2.3889 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                0.917850   0.224929    4.08  6.1e-05 ***\ninput_k                    0.220542   0.064231    3.43   0.0007 ***\noutput_tokens              0.009887   0.000532   18.57  < 2e-16 ***\nmodelmedium               -0.075828   0.278457   -0.27   0.7856    \nmodellarge                -0.613472   0.384691   -1.59   0.1121    \noutput_tokens:modelmedium  0.008135   0.000690   11.80  < 2e-16 ***\noutput_tokens:modellarge   0.021030   0.000749   28.09  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.931 on 243 degrees of freedom\nMultiple R-squared:  0.984,\tAdjusted R-squared:  0.984 \nF-statistic: 2.49e+03 on 6 and 243 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\n## איך קוראים את הפלט {.smaller}\n\n\n\n- **זמן לכל טוקן בתשובה:** 9.9 מילישניות במודל השפה הקטן, 18 בבינוני ו-30.9 בגדול (האמת בסימולציה: 10, 18 ו-30)\n- **`input_k`** מובהק עכשיו: 0.22 שניות לכל אלף טוקנים בקלט. במודלים הקודמים הוא \"הוסתר\" בגלל שגיאה גדולה ($\\hat\\sigma = 3.6$). עכשיו $\\hat\\sigma = 0.93$\n- **`modelmedium`, `modellarge`** לא מובהקים, אבל **לא מוחקים אותם**. כשיש אינטראקציה, הם ההפרש בין מודלי השפה כשאורך התשובה **אפס**, ולא \"ההשפעה של גודל מודל השפה\"\n- **כלל ההיררכיה:** אם אינטראקציה נמצאת במודל, משאירים בו גם את המשתנים שמרכיבים אותה\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(fit3, fit4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: latency ~ input_k + output_tokens + model\nModel 2: latency ~ input_k + output_tokens * model\n  Res.Df RSS Df Sum of Sq   F Pr(>F)    \n1    245 911                            \n2    243 211  2       701 404 <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n# בדיקת ההנחות ([Diagnostics]{.en})\n\n## שאריות מול ערכים חזויים\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nbind_rows(`בלי אינטראקציה (fit3)` = augment(fit3),\n          `עם אינטראקציה (fit4)`  = augment(fit4), .id = \"fit\") |>\n  ggplot(aes(.fitted, .resid, colour = model)) +\n  geom_hline(yintercept = 0, colour = nanas_pal[[\"grey\"]]) +\n  geom_point(alpha = 0.6) +\n  facet_wrap(~ fit, scales = \"free_y\") +\n  scale_colour_manual(values = model_cols) +\n  labs(title = \"השאריות חושפות את מה שהרגרסיה פספסה\",\n       subtitle = \"משמאל: דפוס ברור לפי גודל מודל השפה · מימין: ענן אקראי סביב אפס\",\n       x = \"Fitted value (s)\", y = \"Residual (s)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/resid-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## מה מחפשים בגרף השאריות {.smaller}\n\n| מה רואים | מה זה אומר | מה עושים |\n|---|---|---|\n| ענן אקראי סביב אפס | ההנחות סבירות | |\n| עקומה (קשת) | הקשר לא לינארי | מוסיפים $x^2$, טרנספורמציה ל-$x$ |\n| משפך: הפיזור גדל עם $\\hat y$ | השונות לא קבועה | טרנספורמציה ל-$Y$ (למשל $\\log Y$) |\n| קבוצות עם דפוסים שונים | חסר משתנה או אינטראקציה | מוסיפים אותם למודל |\n| נקודה בודדת רחוקה | ערך חריג | בודקים אותו. לא מוחקים אוטומטית |\n\n**ועוד שתי בדיקות:**\n\n- **נורמליות:** גרף [Q-Q]{.en} של השאריות (`stat_qq()`). עם מדגם גדול, סטיות קטנות לא מזיקות למבחנים\n- **אי-תלות:** אם הנתונים נאספו לאורך זמן, משרטטים את השאריות לפי סדר האיסוף\n\n## שאריות מול התפלגות נורמלית\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(augment(fit4), aes(sample = .std.resid)) +\n  geom_abline(colour = nanas_pal[[\"grey\"]], linetype = \"dashed\") +\n  stat_qq(colour = nanas_pal[[\"primary\"]]) +\n  labs(title = \"השאריות קרובות לנורמליות\",\n       subtitle = \"שאריות מתוקננות של fit4 מול הכמויות של N(0,1)\",\n       x = \"Theoretical quantile\", y = \"Standardised residual\")\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/qq-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## מבחן [Kolmogorov–Smirnov]{.en} לשאריות {.smaller}\n\nגרף Q-Q הוא בדיקה בעין. אפשר גם לבדוק את הנורמליות במבחן, עם מבחן KS מההרצאה על שיטות א-פרמטריות:\n\n$$\nH_0: \\text{השאריות המתוקננות מתפלגות } N(0, 1) \\qquad D = \\max_x \\left| F_n(x) - \\Phi(x) \\right|\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nks.test(rstandard(fit4), \"pnorm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  rstandard(fit4)\nD = 0.046, p-value = 0.7\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n- $D = 0.046 < 0.086 \\approx 1.36/\\sqrt{250}$, ולכן **לא דוחים** את $H_0$. אין עדות לסטייה מנורמליות\n- **הסתייגות:** השאריות מחושבות מהמקדמים שאמדנו, ולכן ה-p-value רק בקירוב (כמו ב-KS עם פרמטרים אמודים). מבחן ייעודי לנורמליות הוא `shapiro.test()`\n- עם מדגם גדול מאוד, KS ידחה גם סטייה זניחה. עם מדגם קטן, הוא לא יזהה גם סטייה גדולה. לכן מסתכלים **גם** על הגרף\n\n## מולטיקולינאריות ([Multicollinearity]{.en}) {.smaller}\n\nמספר המסמכים מ-RAG קובע כמעט לגמרי את מספר הטוקנים בקלט: המתאם ביניהם הוא 0.94. מה קורה כשמכניסים את שניהם?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit5 <- lm(latency ~ input_k + rag_docs + output_tokens * model, data = llm)\nrbind(fit4 = coef(summary(fit4))[\"input_k\", 1:2],\n      fit5 = coef(summary(fit5))[\"input_k\", 1:2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Std. Error\nfit4   0.2205    0.06423\nfit5   0.4372    0.18807\n```\n\n\n:::\n:::\n\n\n- שגיאת התקן של `input_k` גדלה פי 2.9. הרגרסיה לא יכולה להפריד בין שני משתנים שזזים יחד\n- המקדמים \"לא יציבים\": שינוי קטן בנתונים מזיז אותם הרבה. **החיזוי** כמעט לא נפגע. **הפרשנות** נפגעת\n\n**מדד VIF** ([Variance Inflation Factor]{.en}): $R_j^2$ הוא ה-$R^2$ של רגרסיה של $x_j$ על כל שאר המשתנים המסבירים.\n\n$$\nVIF_j = \\frac{1}{1 - R_j^2}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr2_input <- summary(lm(input_k ~ rag_docs + output_tokens * model, data = llm))$r.squared\n1 / (1 - r2_input)    # VIF of input_k. Rule of thumb: above 5-10 is a problem\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.672\n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-format=\"revealjs\"}\nה-VIF הוא בדיוק הפקטור שבו השונות של $\\hat\\beta_j$ גדלה, לעומת מצב שבו $x_j$ לא מתואם עם שאר המשתנים. החבילה `car` מחשבת אותו לכל המשתנים בבת אחת (`car::vif()`). כאן חישבנו אותו ידנית כדי לראות מאיפה הוא מגיע. **מה עושים?** משאירים רק אחד מהמשתנים המתואמים, זה שקרוב יותר למנגנון. כאן הטוקנים בקלט הם מה שהשרת מעבד בפועל, והמסמכים משפיעים רק דרכם.\n:::\n\n# בחירת משתנים ([Variable selection]{.en})\n\n## שלוש גישות {.smaller}\n\n- **קדימה ([Forward]{.en}):** מתחילים ממודל בלי משתנים. בכל צעד מוסיפים את המשתנה שמשפר את הקריטריון הכי הרבה. עוצרים כשאף הוספה לא משפרת\n- **אחורה ([Backward]{.en}):** מתחילים מכל המשתנים. בכל צעד מוציאים את המשתנה שתורם הכי מעט, כל עוד ההוצאה לא פוגעת בקריטריון\n- **בצעדים ([Stepwise]{.en}):** כמו קדימה, אבל אחרי כל הוספה בודקים אם כדאי להוציא משתנה שכבר נכנס\n\n**קריטריונים נפוצים:** $R^2_{adj}$, ה-p-value של מבחן F חלקי, או [AIC]{.en} (מדד שמאזן בין טיב ההתאמה למספר הפרמטרים. קטן יותר = טוב יותר)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_all  <- lm(latency ~ input_k + rag_docs + hour + output_tokens * model, data = llm)\nfit_step <- step(fit_all, direction = \"both\", trace = 0)   # stepwise by AIC\nformula(fit_step)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlatency ~ input_k + hour + output_tokens + model + output_tokens:model\n```\n\n\n:::\n:::\n\n\n## מה יכול להשתבש בבחירה אוטומטית {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(summary(fit_step))[\"hour\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Estimate Std. Error    t value   Pr(>|t|) \n -0.014070   0.008184  -1.719055   0.086883 \n```\n\n\n:::\n:::\n\n\n- `hour` **נשאר** במודל, אף שבסימולציה לשעה אין שום השפעה על זמן התגובה. ה-p-value שלו אפילו קרוב ל-0.05\n- כשבודקים הרבה משתנים, חלקם ייראו מועילים במקרה. האלגוריתם בוחר בדיוק אותם\n- **ה-p-values אחרי בחירה אופטימיים מדי.** המודל נבחר על סמך אותם נתונים שעליהם הוא נבדק\n- **עדיף:** לבנות את המודל מתוך הבנה של המנגנון, ולבדוק אותו על נתונים שלא השתתפו בבנייתו. בפועל מחלקים את הנתונים לשני חלקים: **סט אימון** ([train]{.en}) שעליו בוחרים ואומדים את המודל, ו**סט בדיקה** ([test]{.en}) שעליו בודקים את החיזוי. בקורס בלמידת מכונה תלמדו על כך יותר\n\n# חיזוי ([Prediction]{.en})\n\n## רווח סמך מול רווח חיזוי {.smaller}\n\nלנקודה חדשה $\\mathbf{x}_0 = (1, x_{01}, \\dots, x_{0k})'$, החיזוי הוא $\\hat y_0 = \\mathbf{x}_0'\\hat{\\boldsymbol\\beta}$. יש שתי שאלות שונות:\n\n- **רווח סמך** ([confidence interval]{.en}): איפה **התוחלת** $E(Y \\mid \\mathbf{x}_0)$, זמן התגובה הממוצע של כל הקריאות האלה?\n- **רווח חיזוי** ([prediction interval]{.en}): איפה תיפול **קריאה בודדת** חדשה?\n\n$$\n\\text{CI:}\\;\\; \\hat y_0 \\pm t_{1-\\alpha/2,\\, n-k-1}\\sqrt{\\hat\\sigma^2\\, \\mathbf{x}_0'(X'X)^{-1}\\mathbf{x}_0}\n\\qquad\n\\text{PI:}\\;\\; \\hat y_0 \\pm t_{1-\\alpha/2,\\, n-k-1}\\sqrt{\\hat\\sigma^2 \\left(1 + \\mathbf{x}_0'(X'X)^{-1}\\mathbf{x}_0\\right)}\n$$\n\nה-1 הנוסף ברווח החיזוי הוא השונות של התצפית החדשה עצמה. גם עם אינסוף נתונים הוא לא נעלם.\n\nברגרסיה פשוטה, $\\mathbf{x}_0'(X'X)^{-1}\\mathbf{x}_0 = \\dfrac{1}{n} + \\dfrac{(x_0 - \\bar x)^2}{S_{xx}}$: הרווחים צרים ביותר ב-$\\bar x$ ומתרחבים ככל שמתרחקים ממנו.\n\n## חזרה לשאלה: כמה זמן תיקח הקריאה?\n\n2,000 טוקנים בקלט, 500 בפלט, מודל השפה הגדול:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_call <- tibble(input_k = 2, output_tokens = 500, model = \"large\")\nrbind(confidence = predict(fit4, new_call, interval = \"confidence\")[1, ],\n      prediction = predict(fit4, new_call, interval = \"prediction\")[1, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            fit   lwr   upr\nconfidence 16.2 15.92 16.49\nprediction 16.2 14.35 18.06\n```\n\n\n:::\n:::\n\n\n- **בממוצע**, קריאות כאלה לוקחות בין 15.9 ל-16.5 שניות\n- **קריאה בודדת** תיקח, ב-95% מהמקרים, בין 14.3 ל-18.1 שניות. זה המספר שרלוונטי להתחייבות לזמן תגובה ([SLA]{.en})\n\n::: {.content-hidden when-format=\"revealjs\"}\n**החישוב הידני** של רווח הסמך, עם המטריצה $X$ של `fit4`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nX4 <- model.matrix(fit4)\nx0 <- model.matrix(~ input_k + output_tokens * model,\n                   data = mutate(new_call, model = factor(model, levels(llm$model))))[1, ]\nh0 <- drop(t(x0) %*% solve(t(X4) %*% X4) %*% x0)        # x0' (X'X)^-1 x0\ny0 <- sum(x0 * coef(fit4))\nt_crit <- qt(0.975, df = fit4$df.residual)\nc(fit = y0, h0 = h0,\n  ci_half = t_crit * sigma(fit4) * sqrt(h0),\n  pi_half = t_crit * sigma(fit4) * sqrt(1 + h0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     fit       h0  ci_half  pi_half \n16.20402  0.02422  0.28546  1.85618 \n```\n\n\n:::\n:::\n\n\n$h_0$ קטן מאוד (יש 250 תצפיות, והנקודה לא רחוקה מהן), ולכן רווח החיזוי נקבע כמעט כולו על ידי $\\hat\\sigma$.\n:::\n\n## איך זה נראה\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\ngrid_cpu <- tibble(load = seq(8, 19, by = 0.1))\nbands <- bind_cols(grid_cpu,\n                   predict(fit_cpu, grid_cpu, interval = \"confidence\") |> as_tibble(),\n                   predict(fit_cpu, grid_cpu, interval = \"prediction\") |> as_tibble() |>\n                     select(pi_lwr = lwr, pi_upr = upr))\n\nggplot(bands, aes(load)) +\n  geom_ribbon(aes(ymin = pi_lwr, ymax = pi_upr), fill = nanas_pal[[\"sky\"]], alpha = 0.25) +\n  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = nanas_pal[[\"primary\"]], alpha = 0.35) +\n  geom_line(aes(y = fit), colour = nanas_pal[[\"primary\"]], linewidth = 1) +\n  geom_point(aes(load, util), data = cpu, size = 2.5) +\n  labs(title = \"רווח החיזוי רחב יותר מרווח הסמך, ושניהם מתרחבים בקצוות\",\n       subtitle = \"דוגמת המעבד · כהה: רווח סמך 95% לתוחלת · בהיר: רווח חיזוי 95% לתצפית בודדת\",\n       x = \"Load (k requests / min)\", y = \"CPU utilisation (%)\")\n```\n\n::: {.cell-output-display}\n![](03-multiple-regression_files/figure-html/ci-pi-plot-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n# מה יכול להשתבש\n\n## חמש מלכודות {.smaller}\n\n1. **אקסטרפולציה:** לפי מודל המעבד, ניצולת של 80% תגיע בעומס של כ-57 אלף בקשות בדקה. אבל מדדנו רק בין 10 ל-17. מעבדים בעומס גבוה מתנהגים אחרת (תורים, [throttling]{.en}), והמודל לא יודע על זה כלום\n2. **מתאם אינו סיבתיות:** נתוני הלוגים הם תצפיתיים. אם משתמשים בוחרים במודל השפה הגדול למשימות קשות, ייתכן שגם משהו אחר במשימות האלה מאט אותן. כדי לדעת בוודאות, צריך ניסוי (על כך בהרצאה על תכנון ניסויים)\n3. **$R^2$ גבוה אינו הוכחה:** הוא תמיד עולה כשמוסיפים משתנים. משווים מודלים לפי $R^2_{adj}$, מבחן F חלקי, או ביצועים על נתונים חדשים\n4. **מולטיקולינאריות:** מקדמים לא יציבים ושגיאות תקן גדולות, אף שהחיזוי בסדר\n5. **מודל שגוי מסתיר אפקטים:** `input_k` נראה חסר השפעה עד שהוספנו את גודל מודל השפה והאינטראקציה. **תמיד** מסתכלים על השאריות\n\n# סיכום\n\n## מה לקחת מההרצאה {.smaller}\n\n| השאלה | הכלי | ב-R |\n|---|---|---|\n| מה הקשר בין $Y$ לכל משתנה, כשהשאר קבועים? | $\\hat{\\boldsymbol\\beta} = (X'X)^{-1}X'\\mathbf{y}$ | `lm(y ~ x1 + x2)`, `summary()` |\n| האם משתנה בודד תורם? | מבחן t, $t_{n-k-1}$ | `summary()` |\n| האם המודל כולו מסביר משהו? | מבחן F, $F_{k,\\,n-k-1}$ | שורה אחרונה ב-`summary()` |\n| האם קבוצת משתנים תורמת? | מבחן F חלקי, $F_{q,\\,n-k-1}$ | `anova(reduced, full)` |\n| משתנה קטגורי עם $m$ רמות | $m - 1$ משתני דמה | `factor` |\n| האם השיפוע תלוי בקבוצה? | אינטראקציה | `x * group` |\n| האם ההנחות מתקיימות? | שאריות, Q-Q, VIF | `augment()`, `stat_qq()` |\n| מה צפוי לתצפית חדשה? | רווח סמך / חיזוי | `predict(interval = )` |\n\n- כל מקדם מתפרש **בהינתן שאר המשתנים במודל**. כשמשנים את המודל, משתנה גם הפרשנות\n- את המודל בונים מתוך הבנה של המנגנון. אלגוריתם בחירה הוא כלי עזר, לא תחליף\n",
    "supporting": [
      "03-multiple-regression_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}